### ISSUE TITLE
unable to (re)add new profile after removing

### ISSUE THREAD

**Issue by CelestialMonarchy** [audiamus/BookLibConnect#104]
Hoping somone can help. I recently added three profiles to BookLibConnect which all worked perfectly.  Then I removed one of them by mistake. I followed the instructions to add it again (including deleting the previous device on Amazon's device manager page). The profile added sucessfully.  But now when I click 'Download' none of the content is displayed. Why would the profile be loading but not the content?  (already checked the most obvious thing and made sure I was logged into my Audible account).
Any suggestions appreciated
  

![no content](https://github.com/audiamus/BookLibConnect/assets/133222893/2772921b-9cbe-4b71-8da8-b04c6ef43a8e)

**Comment by audiamus** [comment]
A log file may help here, default log level 3 is sufficient. Run a full Resync with the profile in question.
