### ISSUE TITLE
Does not display every content in library

### ISSUE THREAD

**Issue by XRone99** [audiamus/BookLibConnect#107]
The tool works perfectly exception made for a little issue:
I recently added this: [link](https://www.audible.it/pd/The-Sandman-Atto-III-Podcast/B0BKGZGV63?ref=a_pd_La-loc_c1_podcast-show-details&pf_rd_p=23fc696b-c716-4f5c-a8c6-fc2268366a2f&pf_rd_r=2ARS4TMMVEDCSN5Q6TH4&pageLoadId=ILz3XJQo4usw5gse&creativeId=687df7fe-eab4-4c9a-9aec-36be6c5dfc58) to my library. I can stream it directly from audible but Book Lib Connect is unable to show it in the Library. 
I actually don't know if it's a real bug or just Audible's fault, what I know is that the tool works perfectly with every other book I have in library, included Part I and Part II of the book in question.

**Comment by audiamus** [comment]
If that is a podcast, Book Lib Connect doesn't currently support them. But they are on the the todo list.

**Comment by XRone99** [comment]
Yeah I think It could be categorized as podcast at the Moment, even though the previous two parts of this series were downloadable so categorized as books
