### ISSUE TITLE
Option to auto export into preset folder structure for integration with Audiobook Management software like Audiobookshelf & Jellyfin

### ISSUE THREAD

**Issue by Teekeks** [audiamus/BookLibConnect#109]
It would be helpful if you could export the files to a configurable folder Structure to neatly integrate with Audiobook Management software like [AudioBookshelf](https://www.audiobookshelf.org/), [Jellyfin](https://jellyfin.org/), [Plex](https://www.plex.tv/) or others like it.
The usual Folder structure per Book for these is:

- Series: `<Author>/<Series>/<Book>/<File(s)>`
- Single Book: `<Author>/<Book>/<File(s)>`

**Comment by audiamus** [comment]
My plan is to extend the options in sister tool [AAX Audio Converter](https://github.com/audiamus/AaxAudioConverter) which is the place for file and folder structure and meta data manipulation. AAX Audio Converter comes with several features here, nonetheless I am thinking that some additional ones can be useful. That may include more folder tailoring and also introduce new custom meta tags, in particular for book series. I am playing with [MusicBee](https://getmusicbee.com/) at the moment, which would support such custom meta.  

However, I believe that both your suggestions have already been implemented in current AAX Audio Converter.  See also the AAX Audio Converter manual for examples of the resulting file and folder structures.

Book Lib Connect itself shall stay a "simple" downloader and decrypter, to be merged into AAX Audio Converter eventually.
