### ISSUE TITLE
Wrong ordering of chapters in multi part book

### ISSUE THREAD

**Issue by schlangguru** [audiamus/BookLibConnect#11]
Hi. I downloaded a book with 4 Parts, without checking the 'multipart download' option. So the book got joined to a single m4b file.
But the order of chapters is wrong. It seems to order the chapters with a alphabetical order which leads to an ordering like this:

- chpater 10
- chapter 11
- chapter 1
- chapter 2
- ...

**Comment by audiamus** [comment]
Yep. It's a bug in AAXClean, an integer overflow, occurring for books with "too many" frames, i.e. either very long or high audio quality ones. I'll fix that with the next version, using my own, patched build of AAXClean.

Workarounds at the moment:
- Use multi-part download
- Get the latest FFmpeg version and substitute that in AAX Audio Converter: 
https://github.com/audiamus/BookLibConnect/issues/3#issuecomment-1019936346

**Comment by schlangguru** [comment]
I used the multi-part download to workaround this. Many thanks for the great software.

**Comment by audiamus** [comment]
Fixed in [Version 0.3](https://github.com/audiamus/BookLibConnect/releases/tag/v0.3).
