### ISSUE TITLE
BookLibConnect .aax file doesn't support SanDisk MP3 player Channel Mode

### ISSUE THREAD

**Issue by Sailfish** [audiamus/BookLibConnect#110]
Audible supports the [SanDisk Clip Jam MP3 Player's](https://downloads.sandisk.com/downloads/um/clipjam-um.pdf) AAX feature. BookLibConnect's transcoding to .aax does play on the MP3 player but whenever Forward/Back Chapter or Pause buttons are pressed, the player pauses and when un-paused, restarts from the beginning. Oddly, however, FastForward and FastBack work fine. Note: these use same buttons as Forward/Back Chapter buttons but are distinguished by the player when the person holds them down rather than a quick click.

I've used the AAV Audio Converter on the BookLibConnect .aax file and converted to MP3 Chapter File transcoding and that work but requires a separate step.

**Comment by audiamus** [comment]
Audible files are MPEG4. .aax is .m4b (MPEG4 audio only) with encrypted audio. Book Lib Connect does not modify the audio other than decrypting it. It does not touch meta data all. Basic chapters come embedded with the audio. The separate json file may have more detailed chapters. Many players can read MPEG4 chapters, but there are two variants. It's AAX Audio Converter to tailor your book to the requirements of your player. It will write both variants. 

Book Lib Connect's exported .aax is merely a renamed .m4b file, for compatibility with AAX Audio Converter. To feed a player without further processing by AAX Audio Converter, use the .m4b file directly.

**Comment by Sailfish** [comment]
The SanDisk player doesn't support the .m4b format; only Audible's .aax format (and .mp3.) Perhaps it's the lack encryption that causing the chapter feature loss on the device? My standard listening mode is to download the title .aax file onto the player's Audible folder and they work fine. However, Audible Plus titles are not downloadable so I use the BookLibConnect program to download the title in .aax format then use AXX Audio Converter to convert that into .mp3 format. This is less feature-robust as .aax but it is still usable and still more convenient than using my smartphone.

Thanks for the explanation.

**Comment by audiamus** [comment]
Strange enough. The .aax file created by Book Lib Connect is identical to the .m4b file, only with .aax as file type. These adhere to the MPEG4 standard and its meta data specs, including the two variants for chapters, commonly named "Quicktime" and "Nero". Audible fille only one of the two, I cannot remember which. As said above, AAX Audio Converter writes both. 

MP3, on the other hand, is a different standard, also with completely different meta data specs, known as ID3. The later versions of ID3 have specs for chapters, but very few players support them. MPC-HC on Windows is a positive example that properly processes MP3 chapters. Nonetheless, AAX Audio Converter always creates them, just in case.  

(The original file downloaded from Audible is given the file type .aaxc by Audible. It's still audio-only MPEG4, the difference to Audible .aax files is the enhanced encryption.)

**Comment by Sailfish** [comment]
Interesting. .aaxc is a relatively new format, as I recall and since the SanDisk players have been around for many years and no updates being issued, that could be the problem. I was able to confirm that neither the SanDisk player nor Audible Manager could play it, even though they could detect and display the title information.
