### ISSUE TITLE
Login at Amazon not possible

### ISSUE THREAD

**Issue by BlacksWise** [audiamus/BookLibConnect#111]
Dear Ladies and Gentleman,

Today I installed booklib connect on my PC.  When It try to login to Amazon I receive the following message:

Tut uns leid: Die Web-Adresse, die du eingegeben hast, gibt es auf unserer Website nicht. 

Which translates to the error statet in the following screenshot:
![grafik](https://github.com/audiamus/BookLibConnect/assets/18145578/e62e7dbc-2294-491d-b78b-2a08c9d81f72)

I also tried the other amazon domains and received the same error.

Best regards,
Andre

**Comment by audiamus** [comment]
In deutsch: 

Das ist kein Fehler, das ist das erwartete Verhalten. Bedeutet, dass die Anmeldung erfolgreich war. Die jetzt im Web-Browser angezeigte Adresse (URL) enthält die nötigen Zugangsdaten zum Download vom eigenen Audible-Konto. Adresse vollständig aus dem Browser kopieren und in das freie Textfeld im Book-Lib-Connect-Dialog kopieren. 

Es gibt noch keine deutschsprachige Hilfe zum Programm, aber die englische Anleitung und der Erläuterungstext im Dialog selbst beschreiben genau dieses Vorgehen.

**Comment by BlacksWise** [comment]
Ja, wenn ich in der Lage wäre zu lesen, hätte ich das natürlich auch gesehen, aber manchmal ist man einfach zu doof dafür.

Sorry, für die Umstände und danke für die erläuternden Worte.

**Comment by StevenOnGH** [comment]
For me is the Problem that I get the not allowed side for a really short time (half second d or less) after this I been forwarded to an Audible LogIn Mask and on this side the side adress will not be accepted by booklib - Any ideas?
