### ISSUE TITLE
Downloads not starting

### ISSUE THREAD

**Issue by ablvebird** [audiamus/BookLibConnect#112]
Hi! First of all amazing job, I have been using this app for a couple of years or so and I absolutely love it. Thanks a lot!

Regarding the issue I'm a having, suddenly downloads are not event starting. I have never encountered this issue before, and since there is no error message, I don't think I have any log to share about the problem. Here is a screenshot of the app's state, as it has been for a good time without any perceptible change.

![image](https://github.com/audiamus/BookLibConnect/assets/127777801/e0d75bf7-cab8-4797-87ec-5c4c6541fd05)

Thanks in advance!

**Comment by audiamus** [comment]
Check your download and export destination folders. One or both of them may currently not exist. Book Lib Connect looks for them but doesn't throw a warning at the moment if they cannot be found. It's on the todo list.

**Comment by ablvebird** [comment]
you were absolutely right! thanks a lot.
