### ISSUE TITLE
Some books downloaded without cover data in origin aax file now

### ISSUE THREAD

**Issue by Viel0320** [audiamus/BookLibConnect#113]
Some books downloaded without metadata in origin aax file now.

even directly convert by libconnect, the book will lose cover (but without losing other metadata).

I don't know it's a mistake or designed by amazon.

for example : https://www.audible.co.jp/pd/%E9%A8%8E%E5%A3%AB%E5%9B%A3%E9%95%B7%E6%AE%BA%E3%81%97-%E2%80%95%E7%AC%AC%EF%BC%92%E9%83%A8-%E9%81%B7%E3%82%8D%E3%81%86%E3%83%A1%E3%82%BF%E3%83%95%E3%82%A1%E3%83%BC%E7%B7%A8%EF%BC%88%E4%B8%8B%EF%BC%89%E2%80%95-%E3%82%AA%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E3%83%96%E3%83%83%E3%82%AF/B0BZYR4M24

in addition: do you think the narrator tag should be added to m4b files or other files (maybe composer tag would be a good place).

lol.

**Comment by audiamus** [comment]
Book Lib Connect does not alter any meta or video/image data in the downloaded file, it only tackles audio. You can check that if you enable "Keep encrypted files", which will keep the .aaxc file. Add .mp4 to the file and analyse it with a suitable tool. Even Mp3Tag or MPC-HC would work. You cannot play the .aaxc file, but the cover should be shown - if present, that is. 

> narrator tag

Meta data manipulation will happen in [AAX Audio Converter](https://github.com/audiamus/AaxAudioConverter), the companion to Book Lib Connect. There you can define how to encode the narrator.

**Comment by Viel0320** [comment]
> 
That's what I mean, the cover couldn't be shown.
<img width="764" alt="{5D9C502C-7306-43c8-B0AD-ACB5EEEE8493}" src="https://github.com/audiamus/BookLibConnect/assets/12400928/9f1c2faf-ad06-483c-bfe7-4f139d7a4e1e">

**Comment by Viel0320** [comment]
And for the aax file of this book
<img width="581" alt="{7532CF29-5789-4630-AEEA-A63423A75F8A}" src="https://github.com/audiamus/BookLibConnect/assets/12400928/11bc35cc-1322-4031-90a5-e1a4eb1578b3">

**Comment by Viel0320** [comment]
> narrator tag

for BookLibConnect, I mean to add narrator tag to m4b/mp3 files on the steps of download or export.
🤣

**Comment by Viel0320** [comment]
> narrator tag

ONLY FOR BookLibConnect.

I mean adding narrator tag to m4b/mp3 files on the steps of download or export in BookLibConnect.
🤣

**Comment by Viel0320** [comment]
ok, got it.
