### ISSUE TITLE
Cant visualize any download

### ISSUE THREAD

**Issue by veronicaaraus** [audiamus/BookLibConnect#116]
First of all, thanks very much for this app, I have not been able to use it yet but for sure it is going to be very useful. My issue is that i have already connect my audible account but it does not appear any audiobook in the download section as you can see in the picture.
![image](https://github.com/audiamus/BookLibConnect/assets/145617028/778e0def-267a-4c8a-a333-a372144b2a79)

I tried rebooting the app, removing and adding again my audibe account and unencrypting the configuration. could you help me please with this?

**Comment by audiamus** [comment]
Can you provide a log file?

**Comment by veronicaaraus** [comment]
Hello! yes, here is the last one. Hope it is useful. Thanks.
[BookLibConnect_2023-09-25_007.log](https://github.com/audiamus/BookLibConnect/files/12721303/BookLibConnect_2023-09-25_007.log)

**Comment by audiamus** [comment]
Thank you.

You created a profile for the Audible Spanish region. According to the log, BookLibConnect appears not to find any books for you there.. Are you sure that your books are in that region? And not in the US/worldwide (.com) region? The Spanish region is fairly new.

**Comment by veronicaaraus** [comment]
Mm I would say too that i have a US region account (im from chile) but when I try to do it with that regions it doesnt let me log in

**Comment by veronicaaraus** [comment]
Thanks, it was that. At first i was trying with US account but selecting with pre-Amazon username account, that I do have. But not selecting it made it work.

**Comment by audiamus** [comment]
Great!
