### ISSUE TITLE
How to set up amazon.com.br account?

### ISSUE THREAD

**Issue by fcarreira66** [audiamus/BookLibConnect#117]
First of all, thanks for this amazing application!

I have an Amazon Brazil account, this country cannot be selected in the Book Lib tool. Audible BR was launched a few days ago.
Is there anything I can do? Will it necessary to update the tool?

_Originally posted by @fcarreira66 in https://github.com/audiamus/BookLibConnect/discussions/115_

**Comment by mkb79** [comment]
@audiamus 
To implement the Brazil marketplace you can use the marketplace id A10J1VAYUDTYRN.

I will implement these in my package too. See [here](https://github.com/mkb79/Audible/issues/194). 

Best regards

**Comment by audiamus** [comment]
> To implement the Brazil marketplace you can use the marketplace id A10J1VAYUDTYRN.

Thanks very much. I would have automatically visited your site as the most likely source for the ID. I will add it, it may take a couple of days, though, I'm on holidays.

**Comment by audiamus** [comment]
I have added the Brazil Marketplace in version [0.13](https://github.com/audiamus/BookLibConnect/releases/tag/v0.13):

**Comment by mkb79** [comment]
@audiamus 
I've discovered, that the brazilian login page will redirect you to another page when requesting `ap/maplanding`. I'll hope you have take care about that. [Here](https://github.com/mkb79/Audible/issues/194#issuecomment-1737683369) you can read more.

**Comment by fcarreira66** [comment]
I've just run Book Lib Connect version 0.13 and have confirmed that it said above by mkb79. I've intercepted a HTTP 302 request /ap/maplanding url with an appropriate tool and I got created my profile BR in Book Lib Connect using url returned by tool. As it stands, it will require additional effort from the user. By the way, thanks for version 0.13 that it's working with Audible BR despite this little issue.

**Comment by audiamus** [comment]
> I've intercepted a HTTP 302 request /ap/maplanding url with an appropriate tool and I got created my profile BR in Book Lib Connect using url returned by tool

That's good news! 

Can you write down the necessary steps in a short tutorial, for other future users of the Brazil marketplace? That would be very helpful.

**Comment by mkb79** [comment]
@audiamus 
Maybe you can use the Chrome Addon [Link Redirect Trace](https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh?hl=en). For this purpose.

**Comment by louanfontenele** [comment]
> @audiamus Maybe you can use the Chrome Addon [Link Redirect Trace](https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh?hl=en) for this purpose.

It's worked for Brazilian Account, thanks
