### ISSUE TITLE
Window size and element visibility

### ISSUE THREAD

**Issue by audiamus** [audiamus/BookLibConnect#12]
Users on [Reddit](https://www.reddit.com/r/audible/comments/sckvhr/comment/hu758h2/?utm_source=reddit&utm_medium=web2x&context=3) have reported an issue with the size of one dialog window, visibility of a panel and position of splitter bars.

_Update after feedback, see below: The problem has to do with High DPI screens and upscaling in the Windows settings._

I have created a dummy app for the windows in question. There is no installer, just a zip. 
[BookLibConnect.FormsTest.zip, new version 1.2](https://github.com/audiamus/BookLibConnect/releases/download/v0.2/BookLibConnect.FormsTest.zip)
_(And it doesn't really need the SQLite DLL that comes with it, but it won't start without it, The underlying code is still Book Lib Connect.)_   

![BookLibConnect FormsTest](https://user-images.githubusercontent.com/47717419/151704301-d6f97700-459e-446d-9dd9-ca9e69687391.png)

Please try it. Do the [Try restore] buttons have any effect?

It writes additional log info to 
`C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect.FormsTest\log`
You can upload the log files here. They do not contain sensitive data.

**Comment by MidCtrlDel** [comment]
I am also having this issue, I hope the attached log file can help! 👍 
[BookLibConnect.FormsTest_2022-02-05_001.log](https://github.com/audiamus/BookLibConnect/files/8009596/BookLibConnect.FormsTest_2022-02-05_001.log)

**Comment by audiamus** [comment]
Are you running this on a 4k monitor with increased font size?

**Comment by MidCtrlDel** [comment]
I am in fact, yes. 3840x2160 with 250% scaling.
________________________________

**Comment by MidCtrlDel** [comment]
And this is what is what it looks like on my end (minus the fact that I obfuscated the titles)

![booklibss](https://user-images.githubusercontent.com/99113312/152674064-cb80a3ff-9e34-4d8e-b79e-fd2ccc6abe60.png)

**Comment by audiamus** [comment]
Right. It very much looks like an issue with the underlying .Net WinForms libraries. While they say, they would automatically adapt to high DPI scaling, there may be limits.  

For the top left panel, its left anchor should be the left window border. But that appears to be ignored. The right anchor seems to be observed.

For the bottom panel with the splitter bars, their original positions appear not to be scaled upwards.

I tested on a hi-dpi laptop monitor, but only up to 150%, and it worked there.

**Comment by audiamus** [comment]
I have uploaded a new version of the test:
[BookLibConnect.FormsTest.zip version 1.1](https://github.com/audiamus/BookLibConnect/releases/download/v0.2/BookLibConnect.FormsTest.zip)

Regarding behaviour, the only change I made was to set High DPI awareness to the highest level. It was on a more basic level before.

I also added more log output for some of the elements ("controls"). They also spill out their absolute coordinates on the screen. Still in diagnostic mode.

**Comment by ninjapanzer** [comment]
@audiamus That makes sense, my Surface Pro 7 defaults to 200% scaling and when I adjusted that the buttons came back.

**Comment by audiamus** [comment]
Did you try the latest version of our test program here? 
Same effect? 
In any case I would be grateful for a log file with that new version.

**Comment by ninjapanzer** [comment]
Same effect with the Test Program
[BookLibConnect.FormsTest_2022-02-06_001.log](https://github.com/audiamus/BookLibConnect/files/8010800/BookLibConnect.FormsTest_2022-02-06_001.log)

With Scaling set to 150%
[BookLibConnect.FormsTest_2022-02-06_001.log](https://github.com/audiamus/BookLibConnect/files/8010804/BookLibConnect.FormsTest_2022-02-06_001.log)

**Comment by audiamus** [comment]
Thank you. This gives me an idea what's happening to the buttons. (I haven't yet analysed the other log output.)

**Comment by audiamus** [comment]
While I could not find a pattern behind this behaviour, it appears that some anchor mechanisms for the Windows Forms controls (the visual elements) do not adapt properly to Hi DPI scaling modes at higher settings.

I have modified the hierarchy that contains the affected buttons and tested it for upscaling unto 200%. Works for me on that test system now where I could reproduce the problem before. 

I also now explicitly set the splitter positions as they don't seem to adapt either. 

New version: 
[BookLibConnect.FormsTest.zip version 1.2](https://github.com/audiamus/BookLibConnect/releases/download/v0.2/BookLibConnect.FormsTest.zip)

**Comment by audiamus** [comment]
I have released [Book Lib Connect 0.4](https://github.com/audiamus/BookLibConnect/releases/tag/v0.4) now, with the same modifications as in the test program. I hope it fixes the Hi DPI issues.
