### ISSUE TITLE
BookLibConnect won't launch

### ISSUE THREAD

**Issue by griffin641** [audiamus/BookLibConnect#124]
I've been using BookLibConnect for some time on my 64-bit Windows 7 machine (I support legacy apps).   The drive recently became unbootable, although it is still readable.  I had a new SS drive installed with 64-bit Windows 7, and downloaded a new BookLibConnect, but when I click on the desktop shortcut icon, I see a small turning wheel for just a second, and then nothing.  Yes, I have downloaded and installed "Net 6 Runtime x64 for Windows desktop".  And I have re-downloaded and re-installed BookLibConnect.  Still nothing.

What am I missing?  Is there info on the original drive it needs to run?  Thanks in advance for any help!

**Comment by audiamus** [comment]
The setup will install BookLibConnect in `C:\Program Files\audiamus\BookLibConnect`. But you can move the executable anywhere, as long as you copy:
`appsettings.json`
`e_sqlite3.dll`
and
`BookLibConnect.pdf`
along with the exe
`BookLibConnect.exe`

**Comment by griffin641** [comment]
Yes, the setup DID install each of the files you mentioned (plus
unins000.dat and unins000.exe) in the exact location you mentioned.
However, even if I click on the  BookLibConnect.exe from here, nothing at
all happens.  The program does not launch. (I did notice that the
appsettings.json file seems to be empty.)  Help?

**Comment by audiamus** [comment]
Then I suggest to check your installed .Net runtime again. 

In a command window, try 
`dotnet --list-runtimes`
It should explicitly list a `Microsoft.WindowsDesktop.App 6.0.*` entry.

This is the current version, which you can install over any existing version:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.22-windows-x64-installer


`appsettings.json` is only used as an option to set the log level, but it must be present and have this content:
`
{
  "LogLevel": null
}
`

**Comment by griffin641** [comment]
I ran  dotnet --list-runtimes as you suggested, and it returned an error
stating that, although my .Net runtime was installed correctly, it could
not launch because it was missing some "dependencies" of its own, and it
directed me to a page to install Visual C++ , and a security update.  Once
those were installed, and my machine was rebooted, BookLibConnect worked
like a charm.  So, THANK YOU so much for getting me over the hump!

I just wanted to leave this in case it might help some other user.

**Comment by audiamus** [comment]
> Once those were installed, and my machine was rebooted, BookLibConnect worked like a charm.

Good to hear!
