### ISSUE TITLE
App won't sync my library

### ISSUE THREAD

**Issue by Ela089** [audiamus/BookLibConnect#125]
Hello,

I just downloaded and installed BookLibConnect 0.13.1.0 on Windows 10 (22H2). After successfully adding my Amazon/Audible account the library window just stays empty. When clicking the "Resync" button, the dialogue asks me if I want to do a full library resync. After confirming this, the cursor simply loads/spins for a few seconds and nothing happens.

I already removed my account from BLC, uninstalled and reinstalled BLC and installed dotnet-sdk-6.0.414-win-x64. BookLibConnect is definitely connected to the correct account because it adds devices to my account.

When launching BLC the startup window appears, filling the progress bar to about 15% on "Initializing library..." and then closes itself.

![BookLibConnect Screenshot](https://github.com/audiamus/BookLibConnect/assets/128149152/ca9c118c-639e-4d25-a534-9c2ac8de3c92)

Thank you for your help.

**Comment by audiamus** [comment]
Have you set up your profile for the correct Amazon/Audible region/marketplace?

What does the log file say?

**Comment by rbielaws** [comment]
Perhaps I shouldn't butt in but I had a similar experience when I signed in using my wife's amazon account and thought it's worth mentioning even if it doesn't turn out to apply to your case.  Our accounts are linked so she has access to all my books and I get one just for her occasionally.  She can listen to books I buy without a problem but no books show up in this app when I sign in with her ID.  Only when I use my own ID do I see any books.

**Comment by audiamus** [comment]
I close this for now. Please reopen when you have more information.

**Comment by Ela089** [comment]
Hello once again, and thank you for your quick reply. I was on vacation and could not check the log files until now.

Unfortunately, I don't really know what to look for in the logs, so I attached them.

I definitely added the correct account in the right region to BLC because it does find new audio books I bought after opening this issue but my "old" audio books are still missing. 

I also added another log file from earlier this year when everything seemed to work fine.
For testing purposes I just uninstalled version 0.13.1 via Control Panel > Programs and Features and installed the previously working version 0.12 and now BLC doesn't find any audio books again, even those that were available to download 5 minutes ago.

I now uninstalled v0.12, installed 0.13.1 and renamed the original "BookLibConnect" folder in %localappdata% so a fresh one will be created (which I should have tried from the start, I'm sorry). After initial set up it appears to work and find all my audio books again.

I think my issue is solved and can stay closed, thank you once again.

[BookLibConnect_2023-10-08_001.log](https://github.com/audiamus/BookLibConnect/files/13163970/BookLibConnect_2023-10-08_001.log)
[BookLibConnect_2023-10-25_001.log](https://github.com/audiamus/BookLibConnect/files/13163971/BookLibConnect_2023-10-25_001.log)
[BookLibConnect_2023-04-17_001.log](https://github.com/audiamus/BookLibConnect/files/13164051/BookLibConnect_2023-04-17_001.log)

**Comment by audiamus** [comment]
The log says book meta data was downloaded but then apparently rejected by the local database. 

This could mean that those books were associated with a previous profile. In that case, you can try to start afresh by renaming or even deleting your local database: `C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`. It will be recreated automatically.

**Comment by Ela089** [comment]
Yeah, that's basically what I did by renaming the BookLibConnect folder in appdata\local and it works again. 

Thank you again for your reply and thank you very much for creating BookLibConnect and your aax to mp3 converter
