### ISSUE TITLE
I can't sync my US library

### ISSUE THREAD

**Issue by bybpow** [audiamus/BookLibConnect#126]
I haven't log in in a while and today I updated. Once I did all my books said the key was not valid. I deleted my profile and login again to my US account with Amazon. Once I did the app is not finding any books.

**Comment by audiamus** [comment]
I suspect that you have to renew the access token from time to time. BookLibConnect should do this in the background if you download books on a regular basis. Or you set "Auto-Connect" to true. Then it will renew the token every time you start the app.

No books could mean that they were all associated with your original profile. The log file might tell more. In that case, you can try to start afresh by renaming or even deleting your local database: `C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`. It will be recreated automatically.

**Comment by bybpow** [comment]
Deleting that file solved my issue. Thanks.
