### ISSUE TITLE
 Bibliothek wird nach Anlage von  Profil  nicht geladen.  

### ISSUE THREAD

**Issue by alurio** [audiamus/BookLibConnect#128]
Hallo 

Ich habe den Fehler gemacht mein Gerät /Profil.abzumelden
jetzt funktioniert die neu Registrierung nicht, bzw um präzise zu sein ich durchlaufe den Inital Profil Dialog bekomme die Meldung device registered aber  dann geht es nicht weiter. Der Profildialog ist grau,  die liberary wird nicht geladen. Bin jetzt schon bei Profilversuch 7 . Das Programm zahlt die Versuche sogar weiter, obwohl ich schon 2 mal deinstalliert habe. 

Was geht da schief, was kann ich tun?

**Comment by audiamus** [comment]
Der brutalste Weg ist die lokalen Daten zu löschen:
`C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect`
Darin die Unterverzeichnisse:
- `config`: Enthält Dein (verschlüsseltes) Profil und Zugangs-Token
- `data`: Enthält die lokale SQLite-Datenbank
- `settings`: Deine Benutzereinstellungen

Die werden alle wieder mit Inhalt automatisch neu angelegt. 
Die anderen drei Unterverzeichnisse können bleiben, haben keinerlei Einfluss auf den Zugang.

_Nicht mehr genutzte registrierte "Geräte" solltest Du zusätzlich bei Amazon/Audible wieder löschen, wegen möglicher Obergrenze._

**Comment by alurio** [comment]
Hi. 

 brutaler Weg hat geklappt hab die Datenbank gelöscht, die wurde jetzt neu angelegt und wird wieder geladen.

**Comment by audiamus** [comment]
OK. Es kann sein, dass man bei einem neuen Account auf seine alten Bücher in der lokalen Datenbank nicht mehr zugreifen kann. Das ist eigentlich auch so gewollt, damit man Accounts unabhängig voneinander verwalten kann. Ich hab's auf meiner todo-Liste, aber noch keine einfach zu realisierende und vom Anwender nachvollziehbare Lösung gefunden.
