### ISSUE TITLE
keine Tags wenn m4b-Datei zu groß ist?

### ISSUE THREAD

**Issue by HarveyOs** [audiamus/BookLibConnect#129]
Hi
Ich habe ein sehr großes Hörbuch (Stephen King - The Stand) als eine große Datei geladen. Diese Datei ist dann in m4b umgewandelt ca. 2.9 GB groß. Leider fehlen in dieser Datei dann alle Tags.
Lade ich das Hörbuch in Einzeldateien so funktioniert es.
![image](https://github.com/audiamus/BookLibConnect/assets/63048985/8e0a88d5-8e90-4ddb-a861-237f1004d3ce)

Gibt es auch hier eine 2 GB-Grenze für Dateien?

**Comment by audiamus** [comment]
BookLibConnect fasst die Metadaten nicht an. Die zugrundeliegende AAXClean-Bibliothek bearbeitet nur den AAC-Audio-Datenstrom.

**Comment by HarveyOs** [comment]
Ok. Es scheint ein Problem der von mir benutzten Programme zu sein. Mp3Tag z.B. kann mir die Tags anzeigen.
