### ISSUE TITLE
Audiobook doesn't appear in downloads list

### ISSUE THREAD

**Issue by Jaydezi91** [audiamus/BookLibConnect#131]
So I have an audiobook that doesn't appear in the downloads list. I have bought books before and after the event that do appear for download just not the one in question.

I can confirm that I have indeed bought this book, it appears in my purchases and can be downloaded from the audible website (in 64kb/s) 

The chain of events is as follows,

I downloaded this book from the audible plus catalogue first and enjoyed it enough to want to spend a credit on it.  I then bought the book for one credit so I could continue to enjoy it once my membership ends.  Then I bought a second book not part of the audible plus library.

Today when I opened the book lib connect app, the audible plus book didn't appear in the downloads list although the second book I bought did.  The book appears for download on my wife's profile (who has the book on audible plus but didn't buy it outright) just not on mine.

Using AAX Audio Converter I am able to convert the low quality copy downloaded from Audible's website with no issues, it just doesn't appear in Book Lib Connect which means I am unable to get the higher bitrate version.

Thanks so much for your help and everything you've put into these apps, it's been a huge peace of mind to know I actually own my audiobooks!  Cheers!

**Comment by audiamus** [comment]
It's hard to tell what's going on or not going on here. Log files and the associated json responses in the tmp folder may reveal more. Amazon/Audible internally can link accounts but I doubt this will be shown in the responses BookLibConnect receives. And Audible Plus doesn't seem to be one single service with the same behaviour for all titles.

**Comment by audiamus** [comment]
Closing for the moment. Please reopen once you can provide more information.
