### ISSUE TITLE
Can't get URL with Amazon BR

### ISSUE THREAD

**Issue by Jefik37** [audiamus/BookLibConnect#133]
I make a new profile, select Amazon BR, copy the URL on my browser, but when I login I'm redirected to a 404 page, instead of getting a useful URL. I tested with Amazon US and it works fine.

**Comment by audiamus** [comment]
It's complicated with the Brazil marketplace. I believe you have to intercept the browser response before it redirects you to the 404 page, see here: #117.

**Comment by Jefik37** [comment]
> It's complicated with the Brazil marketplace. I believe you have to intercept the browser response before it redirects you to the 404 page, see here: #117.

The chrome extension there helped me, thank you!

**Comment by audiamus** [comment]
Very good.
