### ISSUE TITLE
Book Lib Connect not reading book in library

### ISSUE THREAD

**Issue by darklingdawns** [audiamus/BookLibConnect#134]
I have a book in my library (The Arrangement, by Mary Balogh) that is not being listed as available to download with Book Lib Connect. I've resynced my library, removed and readded the book to my Audible library, and even deactivated and readded my account to Book Lib Connect, but it continually does not show this book.

**Comment by audiamus** [comment]
Can you provide the log files and json response files? (The latter are in the tmp sub directory,)

**Comment by LostOnTheLine** [comment]
I'm having a similar issue. Mine is actually the 1st one bought on this account. It was "purchased" in 2021 for $0.00. It was a "Free today only" kinda thing, may have been free for that month, I don't remember, but I suspect it is why I cannot see it in the list

**Comment by LostOnTheLine** [comment]
I was able to convert it but had to download it & add it to the other Program with the Activation Code.
