### ISSUE TITLE
failing to create profile due to audible login failure

### ISSUE THREAD

**Issue by campbellca1** [audiamus/BookLibConnect#135]
While trying to create an initial profile, I followed the following steps about 20 times -  

Activate book lib connect
  select "United States"
  select "with pre-amazon user name
  click Create login URL
 click Open URL in default web browser
I enter my user name and password and answer the catpchas 

I then receive "There was a Problem - Your email or password was incorrect, Please try again"
   (I tried copying that URL into the "Copy/Paste URL ,,," block and it responds with "Authorization failed. Please try again")

I never manage to get to the "looking for something?" page described.

(when I open Audible app and login (or go to Amazon and login), Audible opens as it should so I know the web browser, userid and password are functioning)

Consequently, I have been unable to create a profile.  Thoughts?  Suggestions?

Thanks - Cliff

**Comment by audiamus** [comment]
Are you sure you have a pre-Amazon account? Leave that box unchecked and try again.

**Comment by campbellca1** [comment]
As I stated in my original query, I can log into both Amazon.com and Audible.com using the default web browser so I’m certain I have viable account logins to both sites, but I will try your suggestion.  ThanksSent from my iPhoneOn Nov 29, 2023, at 3:57 AM, audiamus ***@***.***> wrote:﻿
Are you sure you have a pre-Amazon account? Leave that box unchecked and try again.

**Comment by campbellca1** [comment]
I tried it without checking the nox per your suggestion and that worked PDQ!  Thank you!!Sent from my iPhoneOn Nov 29, 2023, at 9:54 AM, Cliff Campbell ***@***.***> wrote:﻿As I stated in my original query, I can log into both Amazon.com and Audible.com using the default web browser so I’m certain I have viable account logins to both sites, but I will try your suggestion.  ThanksSent from my iPhoneOn Nov 29, 2023, at 3:57 AM, audiamus ***@***.***> wrote:﻿
Are you sure you have a pre-Amazon account? Leave that box unchecked and try again.

**Comment by audiamus** [comment]
> As I stated in my original query, I can log into both Amazon.com and Audible.com

Even on Audible.com you would log in with your Amazon account and the login page should state that in the header. You have to explicitly switch to a different login page, typically a link named "log-in with a user name" or similar. 

Pre-Amazon accounts are those accounts that were created when Audible was still an independent company.  They continue to work under Amazon rule. Amazon purchased Audible in 2008, but allowed new Audible user name accounts for a few years longer. For quite some time now Amazon recommends to migrate/merge such legacy accounts to/with your Amazon account and many users have done that.
