### ISSUE TITLE
Greyed out "Run" button

### ISSUE THREAD

**Issue by fru** [audiamus/BookLibConnect#136]
Hey,
thank you for this awesome software :-)

I currently can't get the downloading to work. The run button is simply allways greyed out. 

![grafik](https://github.com/audiamus/BookLibConnect/assets/3080261/22c15a64-595f-45fa-b0f1-0176c0124762)
[ProductResponse_B09MVBBTBN-2023_12_05-10_54_53.json](https://github.com/audiamus/BookLibConnect/files/13554957/ProductResponse_B09MVBBTBN-2023_12_05-10_54_53.json)
[BookLibConnect_2023-12-05_003.log](https://github.com/audiamus/BookLibConnect/files/13554958/BookLibConnect_2023-12-05_003.log)

**Comment by audiamus** [comment]
The **Download** or **Export** folders you selected when starting BookLibConnect the first time may no longer exist. The program checks their presence before enabling the **Run** button. See also here: #76

**Comment by fru** [comment]
Thank you very much 😃 That was the problem. I checked the export option but did not select a folder 🙈
