### ISSUE TITLE
Content license denied. Check your Audible account to see if you have access to this file

### ISSUE THREAD

**Issue by maoso** [audiamus/BookLibConnect#139]
Thank you very much for your great project. 

I have liberated around 200 books of around 370. After that 200 all the boos started to get an error 'License Denied' in to the rest 170 books.

![image](https://github.com/audiamus/BookLibConnect/assets/6972854/972870a8-1d8c-4ca1-8b6f-ddf5c6e1208e)

I have web access to the books and I can listen to them with my paid account. 

Any idea about how to solve this issue?

Thank you very much

**Comment by audiamus** [comment]
Are you sure you are in the right forum? This is [BookLibConnect](https://github.com/audiamus/BookLibConnect) here.

**Comment by maoso** [comment]
Sorry I thought that was about libation app. Going to close this issue then. 

Thank you very much
/Jose Mascaro
