### ISSUE TITLE
Profile creation issue

### ISSUE THREAD

**Issue by engdarkalchemist** [audiamus/BookLibConnect#141]
I have a Prime subscription with Audible. But I'm unable to get the authorization. How fix it?
<img width="636" alt="BookLibConnect-profile-creation-issue" src="https://github.com/audiamus/BookLibConnect/assets/84588028/a126b245-59df-4ca9-a51f-0ea2e66fd338">

**Comment by audiamus** [comment]
Is` https://www.amazon.com` the URL you copied from the "Looking for something" web page?
