### ISSUE TITLE
RUN Wont turn solid and allow downlod

### ISSUE THREAD

**Issue by huggieuk** [audiamus/BookLibConnect#142]
hi, i am new to using the app, i have downloaded books previously without issue however now it wont allow me to download a book. 

![image](https://github.com/audiamus/BookLibConnect/assets/158344120/fbf134a5-410b-427b-8454-69b7ec5999a5)

as you can see the RUN Button dont turn solid can you help

**Comment by rodrigo081089** [comment]
Im having the same issue

**Comment by audiamus** [comment]
The Download or Export folders you selected when starting BookLibConnect the first time may no longer exist. The program checks their presence before enabling the Run button. See also here: #136

**Comment by huggieuk** [comment]
That was ot thank you very much
