### ISSUE TITLE
Run button is grayed out

### ISSUE THREAD

**Issue by luttman** [audiamus/BookLibConnect#144]
Tried to reinstall the whole program. 
Windows Server 2022

![image](https://github.com/audiamus/BookLibConnect/assets/3317155/5ab35309-5f88-420e-86a9-044c256bcbf7)

[BookLibConnect_2024-02-14_001.log](https://github.com/audiamus/BookLibConnect/files/14283681/BookLibConnect_2024-02-14_001.log)

**Comment by audiamus** [comment]
The **Download** or **Export** folders you selected when starting BookLibConnect the first time may no longer exist. The program checks their presence before enabling the **Run** button. See also here: #142 and #136.

**Comment by AumCoin** [comment]
I'm having this issue and the folders exist.
