### ISSUE TITLE
Add support for the arm version of Windows

### ISSUE THREAD

**Issue by bergje4** [audiamus/BookLibConnect#147]
I would like to run the installer & software on the arm version of Windows. Currently it is not possible to install the software on arm Windows.

**Comment by audiamus** [comment]
As I don't have a Windows ARM system and don't plan for one, I am not able to test this. And I have no idea whether the app would work or not, particularly as it uses some lower level Win32 API calls. But you can try yourself. It's Open Source and the Visual Studio project files are included.
