### ISSUE TITLE
Handle connection errors better

### ISSUE THREAD

**Issue by hjk321** [audiamus/BookLibConnect#149]
When there's an SSL error, the software will fail silently instead of showing the user a message. It will appear as if you have 0 books available to download. The user currently has to A) check the logs and B) have enough tech experience to know what an ssl error is, in order to know what the problem is.
[BookLibConnect_2024-03-15_003.log](https://github.com/audiamus/BookLibConnect/files/14620602/BookLibConnect_2024-03-15_003.log)

**Comment by audiamus** [comment]
Apparently, I didn't test without an internet connection. I've put it onto the to-do list.
