### ISSUE TITLE
Library empty or Activationcode

### ISSUE THREAD

**Issue by Sunshine11011505** [audiamus/BookLibConnect#152]
Ich hab das Problem an den Aktivierungsschlüssel ran zu kommen. Ich habe je zwei .de, einen .com, .co.uk... Account. Und anfangs hat es mit Booklib funktioniert aber jetzt zeigt er mir für den zweiten US Account keine Bücher an. Kann mir wer mit dem Problem helfen? Ich habe auch schon alle Profile gelöscht und dann neu erstellt.

Wenn ich es ohne Booklib versuche brauche ich den Aktivierungsschlüssel. Wie kann ich mich im Manager auf einem anderen als dem deutschen Account anmelden? Oder wie bekomm ich aus Audible Sync den Aktivierungscode?

I'm having trouble getting the activation key. I have two .de, a .com, .co.uk... account. And initially it worked with Booklib but now it doesn't show me any books for the second US account. Can anyone help me with the problem? I already tried to delete all profiles and created them new - didn't work. 

If I try without Booklib I need the activation key. How can I log in to the manager on an account other than the German one? Or how do I get the activation code from Audible Sync?

Thanks a lot for your help - 1000 Dank für Hilfe im Voraus!

**Comment by audiamus** [comment]
_Just for terminology: There are no "activation codes" with the Audible API that Book Lib Connect is using. Here, every single of your book purchases comes with ist own individual key, or more precisely a pair of IV (seed) and key. Audible calls that a "voucher"._ 

With three different Audible accounts you will have to create three different profiles in Book Lib Connect. Did you do that?

**Comment by Sunshine11011505** [comment]
My husband and I have an account on .de, .com, .co.uk... each. I connected Book Lib with my accounts and everything went well. Then I deleted my profiles (unfortunately I'm not able to have to german profiles in Booklib, that would be awesome) and tried with my husbands. And then the library is empty. Same for .de, .com, .co.uk and so on.

**Comment by audiamus** [comment]
If you deleted your profiles I suggest to start afresh. 

Delete the file that holds the previous configuration. i.e. your profiles or what's left of it :
`C:\Users\<User>\AppData\Local\audiamus\BookLibConnect\config\Configuration.json`

Delete the local BLC database:
`C:\Users\<User>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`

Recreate your profiles, a separate one for each of your Audible accounts, Select the correct Audible region/domain/marketplace for each.

If that still doesn't work we can inspect the log files.

**Comment by Sunshine11011505** [comment]
It worked, thank you!!
