### ISSUE TITLE
Support for Supplemental PDFs?

### ISSUE THREAD

**Issue by colvdv** [audiamus/BookLibConnect#153]
I noticed that I don't have the supplemental PDFs for a book I downloaded, only the mp3 files.

Is this a feature, or do I need to manually grab them?

(I used AAX Audio Converter to convert)

**Comment by colvdv** [comment]
I just checked and other audiobooks downloaded do indeed have the supplemental PDFs with them. Is there a setting someplace that I need to enable this feature? I recently reinstalled both BookLibConnect and AAXAudioConverter, maybe I missed something?

**Comment by audiamus** [comment]
No, those PDFs are not yet supported. They are on the todo list but I don't seem to find the time to implement it, dealing with three other software projects now, in three different and completely unrelated domains. What I noticed, though, that for certain books where your really want to have that sort of non-audible material, e.g. drawings, photographs, maps etc, Audible doesn't provide it.
