### ISSUE TITLE
404

### ISSUE THREAD

**Issue by gustavoleo** [audiamus/BookLibConnect#157]
hello there

thanks for sharing it 

https://www.amazon.com.br/ap/signin?openid.oa2.response_type=code&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=uKN5wRw9If2qxLtZ_5FJBMrECgEFeMyEmpe5FZW8flE&openid.return_to=https%3A%2F%2Fwww.amazon.com.br%2Fap%2Fmaplanding&openid.assoc_handle=amzn_audible_ios_br&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A3943464235354436463830373437413542353732324142463734383237453134234132435a4a5a474c4b324a4a564d&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&marketPlaceId=A10J1VAYUDTYRN&openid.oa2.scope=device_auth_access&forceMobileLayout=true&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0

im getting a 404 back

**Comment by audiamus** [comment]
Brazil is a special case, see #133 and #117.
