### ISSUE TITLE
BookLibconnect no longer creating decrypted exported files

### ISSUE THREAD

**Issue by condoghost** [audiamus/BookLibConnect#162]
Windows 11 BookLibConnect initiates database displays library content. I have 9 new audible books to download, decrypt and export. No matter I select all or just one to Add selected and OK, after I select 'Run' there is no output in the download folder and the export folder. No idea 'why', all was working a-okay when I last ran BookLibConnect 10 July 2024.
I'm thinking maybe I remove the program and files and start over, how do I do that?
Thank-you.

**Comment by audiamus** [comment]
The "Run" button was enabled? You clicked it and then? Did the progress bars show progress? Did the download state change (icons in the first column)? If yes to all those, then the download and export folders are not the ones you expect. Check the settings for both.

**Comment by condoghost** [comment]
Sorry to be wasting your time audiamus. it's just dawned on me: "Of course I can't see the files in the Download folder and Export folder clicking those 'settings' buttons, I've got to open the folders directly!" My going-on 73-year-old-brain has  suddenly gotten befuddled, I've gone daft as a brush. All is okay, all files are there directly  in the correct folders - silly me. Thank-you for your patience ...
