### ISSUE TITLE
Problem with library appearing empty after first succesfull download

### ISSUE THREAD

**Issue by taladro** [audiamus/BookLibConnect#165]
Hi, first of all thanks a million for this software. I swim and love to have my podcasts on my swimheadphones and in Spain Audible doesn´t offer LibSync so your program saved me.
I was able to download some podcasts I´m following  ̶ ̶b̶u̶t̶ ̶t̶h̶e̶r̶e̶ ̶i̶s̶ ̶o̶n̶e̶ ̶c̶a̶l̶l̶e̶d̶ ̶S̶4̶n̶t̶u̶a̶r̶i̶o̶ ̶(̶e̶x̶c̶h̶a̶n̶g̶e̶ ̶t̶h̶e̶ ̶4̶ ̶f̶o̶r̶ ̶a̶ ̶a̶)̶,̶ ̶I̶D̶ ̶B̶0̶9̶7̶P̶Z̶R̶K̶J̶T̶,̶ ̶t̶h̶a̶t̶ ̶d̶o̶e̶s̶n̶´̶t̶ ̶s̶h̶o̶w̶ ̶o̶n̶ ̶t̶h̶e̶ ̶d̶o̶w̶n̶l̶o̶a̶d̶ ̶w̶i̶n̶d̶o̶w̶.̶ ̶
Do you know why that may be happening?

thanks again

**Comment by taladro** [comment]
update, after first successful run now when I add more titles to my library over the web and later try to resync in book lib connect the list appears empty. So it seems as the problem was not the title, but the problem seems like it doesn´t find my library any more. Tried deleting profile and creating a new one, tried uninstalling deleting everything and reinstalling, still the same problem.

After watching the logs, on them it states 28 titles, but on the download window only 6 appear.

20:38:14.568 0001 [AudibleClient.ConfigFromFileAsync] 
20:38:14.569 0001 [BookLibrary.GetAccountAliases] >>> 
20:38:14.864 0001 [BookLibrary.GetAccountAliases] #contexts=0
20:38:14.864 0001 [BookLibrary.GetAccountAliases] <<< 
20:38:14.867 0001 [Authorize.RefreshTokenAsync] >>> auto=False, onAutoRefeshOnly=True
20:38:14.867 0001 [Authorize.readConfigurationAsync] >>> 
20:38:14.867 0001 [Authorize.readConfigurationAsync] <<< 
20:38:14.867 0001 [Authorize.RefreshTokenAsync] <<< auto=False, onAutoRefeshOnly=True
20:38:14.868 0001 [BookLibrary.GetAccountId] >>> 
20:38:15.049 0001 [BookLibrary.GetAccountId] <<< 
20:38:15.050 0001 [MainForm.getAccountAlias] >>> 
20:38:21.006 0001 [MainForm.getAccountAlias] <<< 
20:38:21.007 0001 [BookLibrary.setAccountAlias] >>> id = 1, alias = "Account 1"
20:38:21.060 0001 [BookLibrary.setAccountAlias] <<< id = 1, alias = "Account 1"
20:38:21.062 0001 [MainForm.initLibraryAsync] >>> settings: auto refresh=False, auto update=True
20:38:21.070 0001 [AudibleApi.GetLibraryAsync] >>> resync=False
20:38:21.070 0001 [BookLibrary.GetAccountId] >>> 
20:38:21.072 0001 [BookLibrary.GetAccountId] <<< 
20:38:21.552 0001 [AudibleApi.GetLibraryAsync] page=1, file="LibraryResponse-2024_08_31-20_38_21.json"
20:38:21.576 0001 [AudibleApi.GetLibraryAsync] #items/page=28
20:38:21.684 0001 [AudibleApi.GetLibraryAsync] page=2, file="LibraryResponse-2024_08_31-20_38_21_685.json"
20:38:21.685 0001 [BookLibrary.AddRemBooksAsync] >>> #items=28, resync=False
20:38:21.718 0016 [BookLibrary.addPageBooks] >>> #items=28

Thanks

**Comment by audiamus** [comment]
Podcasts, if categorized as such by Audible, are not supported by BookLibConnect. Their structure collides with the internal design for audio books in BookLibConnect

If for ordinary audio books the log file indicates some sort of success, a couple of corresponding `LibraryResponse*.json` files should be found in the `\audiamus\BookLibConnect\tmp` folder. They will have more details.

**Comment by taladro** [comment]
Thanks a lot for your ultra fast answer, it´s strange as two of the four that show up on the app and I could download are podcasts. In the folder you say there are some 300kb .json files and some 1kb.
I managed to download the podcasts also on an android tablet, may I be able to decrypt those .exo files using your program?
What would you recommend me in order to download those podcasts?

**Comment by taladro** [comment]
I was able to download them using https://github.com/mkb79/audible-cli/
