### ISSUE TITLE
Run button grayed out when selecting titles to be downloaded.

### ISSUE THREAD

**Issue by maciak** [audiamus/BookLibConnect#167]
Hi,
I did not have this issue before but it started today.
When I select a book from my library to be downloaded The Run button is just grayed out and I have no idea why. Do you have any suggestions on what could be happening? I have already removed it while config and reinstalled the app but it's the same all the time :<
My version is the latest one: 0.13.1

**Comment by audiamus** [comment]
Make sure the download (and export) folder actually exist, particularly if you set them to locations on remote drives.

**Comment by nikolajvh** [comment]
@maciak Did you figure out a solution for this.
I also started having this problem today. I made sure that Download and Exportfolder was local and exsisted

**Comment by audiamus** [comment]
>  I made sure that Download and Exportfolder was local and exsisted

... and some titles in the main window are actually selected?

These are the only conditions for the Run button to become enabled.

**Comment by maciak** [comment]
Hmm, After just few days without doing anything I can download titles again. That is super strange. And no my download and export folders are on my local disk so nothing changed there also.
