### ISSUE TITLE
Cant See all Books

### ISSUE THREAD

**Issue by smooth-baking-powder** [audiamus/BookLibConnect#168]
Hi,

i only can see the newest book. Older ones in my library i cant see or download. how can i fix it?

thanks

**Comment by audiamus** [comment]
Have you tried the full Reync? (See the user guide for details.)

If that gives no better result, delete the local database, Book Lib Connect will rebuild it.
`C:\Users\<User>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`

**Comment by alurio** [comment]
Hallo Audimaus .
Ich habe auch Probleme mit der nicht Anzeige von Büchern. Nach jedem zweiten Buch Einkauf fehlt dass jeweils zuletzt gekaufte Buch in der Liste und Resync bleibt ohne Effekt    Die Datenbank zu löschen und neu anlegen zu lassen hilft zwar, aber alle paar Wochen die Datenbank löschen damit alle  Bücher erfasst werden ist auf die Dauer doch etwas nervig. 
Vielleicht findest du ja bei Gelegenheit Zeit das zu Analysieren ich liefere auch gerne irgendwelche Protokolldateien oder ähnliches zu falls Booklibconnect im Hintergrund sowas produziert. Vielleicht ist da ja irgendwo ein kleiner Bug oder man muss was anpassen, weil Audible was geändert hat und nach einem kleinen Update ist wieder Ruhe.

Viele Grüße

**Comment by smooth-baking-powder** [comment]
> Have you tried the full Reync? (See the user guide for details.)
> 
> If that gives no better result, delete the local database, Book Lib Connect will rebuild it. `C:\Users\<User>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`

this solved my problem

**Comment by audiamus** [comment]
>  Vielleicht ist da ja irgendwo ein kleiner Bug oder man muss was anpassen, weil Audible was geändert hat und nach einem kleinen Update ist wieder Ruhe.

Ich glaube nicht, dass Audible hier was geändert hat. Dieses Problem haben einzelne andere Nutzer auch schon früher gemeldet. Aber ich habe bisher keine Anhaltspunkte finden können, woran es liegen könnte - und kann es selber auch nicht reproduzieren.

**Comment by alurio** [comment]
Hi
Hmm wenn es so gar keinen Anhaltspunkt gibt ist das natürlich doof. Dann werde ich damit Leben und vielleicht Mal testweise  deinstallieren neu installieren.

Grüße
