### ISSUE TITLE
Meine Hörbücher werden nicht gefunden. My audiobooks cannot be found.

### ISSUE THREAD

**Issue by Benutzer100** [audiamus/BookLibConnect#174]
Habe 5 Profile, wo alles funktioniert. Habe nun ein neues Audible Konto angelegt mit 6 Hörbüchern, aber sie werden nicht angezeigt. Wohin kann ich die LOG-Datei schicken?
I have 5 profiles where everything works. I have now created a new Audible account with 6 audio books, but they are not displayed. Where can I send the LOG file?

**Comment by audiamus** [comment]
Ich habe ein Konto bei Reddit.com, ebenfalls als "audiamus". Dort kann man an persönliche Nachrichten auch Anhänge anheften.

**Comment by Benutzer100** [comment]
Reicht Ihnen die Log-Datei? 

Und sind in dieser Datei irgendwelche persönlichen Daten drin, die nicht jeder sehen sollte? wie kann ich verhindern, dass alle sie sehen?

Is the log file enough for you?

And is there any personal data in this file that not everyone should see? How can I prevent everyone from seeing it?

**Comment by audiamus** [comment]
Je nach Funktion werden in der Logdatei auch Buchtitel aufgelistet, bei Nicht-Standard-Konfigurationenen eventuell auch der eigene Windows-Benutzername. Audible/Amazon-Benutzername oder Password sind BookLibConnect sowieso nicht bekannt und das Zugangstoken wird nie in einer Logdatei zu finden sein.

BookLibConnect listet zusätzlich die Antworten des Audibe-Web-Servers als json-Dateien. Je nach Fehler kann man daraus noch mehr zur Ursache entnehmen.

Alles, was hier bei GitHub gepostet wird ist öffentlich. Persönliche Nachrichten, ggf mit Anhang, gerne über Reddit.

**Comment by Benutzer100** [comment]
Danke! Werde alles bei Reddit schicken. Danke.
