### ISSUE TITLE
How to compile in Ubuntu?

### ISSUE THREAD

**Issue by apandada1** [audiamus/BookLibConnect#23]
Is there any way to compile this software in GNU/Linux operating systems like Ubuntu?

**Comment by alurio** [comment]
The Problem is that this software  needs the windows specific  .Net Framework. So a transfer into the Linux eco System will not work, as far as I understand

**Comment by audiamus** [comment]
Indeed, it is. While written in C# and for .Net, not all parts of modern .Net are portable, particularly not the GUI components. There are also some Win32-API dependencies at the bottom layer. Therefore it was easier to build almost every assembly in this solution for the Windows desktop SDK of .Net.

Sorry for that, but it was never the intention to build something platform independent here. I have written a number of .Net applications in my professional work that run on Linux, from backend server to tiny IIOT systems, and it's real fun working with the Linux support of Visual Studio these days, but being server-side, none of those applications has a GUI.

**Comment by colvdv** [comment]
I got it running successfully on Fedora 41 using Wine.

View the discussion here: https://github.com/audiamus/BookLibConnect/discussions/196
