### ISSUE TITLE
Specific title is not showing in library

### ISSUE THREAD

**Issue by Jasemat05** [audiamus/BookLibConnect#28]
Hello,

There is a specific title, that's not showing in Book Lib Connect. I've tried it with three Audible Accounts...
https://www.audible.de/pd/Stadt-der-Haie-Hoerbuch/B076KML76M?qid=1646048213&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=e54013e2-074a-460e-861f-7feac676b789&pf_rd_r=WSAD4XR7K7AZ3CNPGS3V
What's the problem?

Greetings

**Comment by audiamus** [comment]
You can check the LibraryResponse.json files in the tmp directory: `C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect\tmp`. They will list all the titles which Audible returns for your account. Use the Resync function to get the full list. (You will have to reformat the json reply to make it readable.)

**Comment by Jasemat05** [comment]
The title is showing in the library response file, I think. But the resync function didn't help to show the title in the list. What do you mean with reformat?

**Comment by audiamus** [comment]
Could you make an extract of the library response file with only that title and upload that extract (see below)? 

> What do you mean with reformat?

The JSON replies come in condensed form and are hard to read. Reformatting means bringing back line feeds and indentation. 
An easy way to do that is with [Visual Studio Code](https://code.visualstudio.com/), a rather light weight code editor (not to be confused with the full Visual Studio IDE). Open the json file, then Ctrl+A to select all text, followed by Ctrl+K, Ctr+F to reformat. 

Each title in the json file starts with 
```
{
            "amazon_asin": 
```

and ends with

```
{
            "title":  ,
            "voice_description": ,
            "ws4v_companion_asin":  
```

The ```"title"``` field is the one to identify our suspicious candidate.

**Comment by Jasemat05** [comment]
When I press CTRL+K CTRL+F, following message aprears:
"Warnung: Invalid regular expression: / \{"items":\[\{"amazon_asin":null,"asin":"B076KML76M","audible_editors_summary":null,"author_pages":null,"authors":\[\{"asin":null,"name":"Aimée Carter"\}\],"availability":null,"available_codecs":\[\{"enhanced_codec":"LC_128_44100_stereo","format":"Enhanced","is_kindle_enhanced":true,"name":"aax_44_128"\},\{"enhanced_codec":"format4","format":"Format4","is_kindle_enhanced":false,"name":"format4"\},\{"enhanced_codec":"LC_64_44100_stereo","format":"Enhanced","is_kindle_enhanced":true,"name":"aax_44_64"\},\{"enhanced_codec":"mp444128","format":"Enhanced","is_kindle_enhanced":true,"name":"mp4_44_128"\},\{"enhanced_codec":"mp44464","format":"Enhanced","is_kindle_enhanced":true,"name":"mp4_44_64"\},\{"enhanced_codec":"aax","format":"Enhanced","is_kindle_enhanced":false,"name":"aax"\}\],"badge_types":null,"badges":null,"benefit_id":null,"buying_options":null,"category_ladders":\[\],"claim_code_url":null,"collection_ids":null,"content_delivery_type":"SinglePartBoo..."
Seems not to function...

**Comment by audiamus** [comment]
Open the library response json file in VS Code. The status bar at the bottom right should say `UTF-8`, `LF` and `JSON`. The content in the text window should be a multi-line bunch of text without any visible structure. Press Ctrl+A keys at the same time. All text should be selected now. Press Ctrl+K keys and within one second Ctrl+F. You don't have to release the Ctrl key between these key strokes. (After you'd pressed Ctrl+K the status bar at the bottom left should say: `(Ctrl+K) was pressed. Waiting for second key of chord...`). The text should now be nicely formatted with line breaks and indentation.

I don't think you will need any extra plug-ins for this. But you can check that you have JSON support: From the `File` menu go to `Preferences`, then `Settings`. Expand `Extensions` in the main window. Click on `JSON`. `JSON Format Enable` should be enabled.

**Comment by Jasemat05** [comment]
Ok, now I managed to reformat the file. What exactly should I send you?

**Comment by audiamus** [comment]
I would need the entire "Item" for this particular title, starting with the opening brace and ending with the closing brace, as explained in the previous comment above: https://github.com/audiamus/BookLibConnect/issues/28#issuecomment-1059389978.

**Comment by Jasemat05** [comment]
Here you are. It's the only title in the file.
{
  "items": [
    {
      "amazon_asin": null,
      "asin": "B076KML76M",
      "audible_editors_summary": null,
      "author_pages": null,
      "authors": [
        {
          "asin": null,
          "name": "Aimée Carter"
        }
      ],
      "availability": null,
      "available_codecs": [
        {
          "enhanced_codec": "LC_128_44100_stereo",
          "format": "Enhanced",
          "is_kindle_enhanced": true,
          "name": "aax_44_128"
        },
        {
          "enhanced_codec": "format4",
          "format": "Format4",
          "is_kindle_enhanced": false,
          "name": "format4"
        },
        {
          "enhanced_codec": "LC_64_44100_stereo",
          "format": "Enhanced",
          "is_kindle_enhanced": true,
          "name": "aax_44_64"
        },
        {
          "enhanced_codec": "mp444128",
          "format": "Enhanced",
          "is_kindle_enhanced": true,
          "name": "mp4_44_128"
        },
        {
          "enhanced_codec": "mp44464",
          "format": "Enhanced",
          "is_kindle_enhanced": true,
          "name": "mp4_44_64"
        },
        {
          "enhanced_codec": "aax",
          "format": "Enhanced",
          "is_kindle_enhanced": false,
          "name": "aax"
        }
      ],
      "badge_types": null,
      "badges": null,
      "benefit_id": null,
      "buying_options": null,
      "category_ladders": [],
      "claim_code_url": null,
      "collection_ids": null,
      "content_delivery_type": "SinglePartBook",
      "content_level": null,
      "content_rating": null,
      "content_type": "Product",
      "continuity": null,
      "copyright": null,
      "credits_required": null,
      "customer_reviews": [
        {
          "asin": "B076KML76M",
          "author_id": "amzn1.account.AHKJUYKRV76NABLE4I4BQH22UG6Q",
          "author_name": "Amazon Kunde",
          "body": "Klasse specher. super geschichte. macht einfach Süchtig.warte nur auf die Fortsetzung. gibt es da schon ein Termin ?",
          "customer_vote": null,
          "format": "Freeform",
          "guided_responses": null,
          "id": "bbd34992787840b1b398f2c12c9cd37d",
          "location": null,
          "ratings": {
            "overall_rating": 5,
            "performance_rating": 5,
            "story_rating": 5
          },
          "review_content_scores": {
            "content_quality": 90,
            "num_helpful_votes": 8,
            "num_unhelpful_votes": 0
          },
          "submission_date": "2018-01-07T22:36:32Z",
          "title": "super klasse gesprochen. "
        },
        {
          "asin": "B076KML76M",
          "author_id": "amzn1.account.AFV7O6IVNO2V4GLF6WORNHKZMFBQ",
          "author_name": "Claudia",
          "body": "Nur eine Frage: wann werden Band 4 und 5 auf audible veröffentlicht? meine Jungs wollen wissen, wie es weitergeht!",
          "customer_vote": null,
          "format": "Freeform",
          "guided_responses": null,
          "id": "c7570349a9f24b8981677c9d4187c1f5",
          "location": "Niedersachsen",
          "ratings": {
            "overall_rating": 5,
            "performance_rating": 5,
            "story_rating": 5
          },
          "review_content_scores": {
            "content_quality": 80,
            "num_helpful_votes": 3,
            "num_unhelpful_votes": 0
          },
          "submission_date": "2019-12-10T20:15:58Z",
          "title": "schöne hörbuchreihe"
        },
        {
          "asin": "B076KML76M",
          "author_id": "amzn1.account.AFSF3PEIFOCKJE66H6TZMTF4BURA",
          "author_name": "Einkaeufer",
          "body": "Super.. <br />- buch<br />-sprächer<br /><br /><br />Ich mag animox deshalb bitte ich die Bücher weiter zu lesen. <br />",
          "customer_vote": null,
          "format": "Freeform",
          "guided_responses": null,
          "id": "f660d4e99629475d85fe14c24d2631b4",
          "location": null,
          "ratings": {
            "overall_rating": 5,
            "performance_rating": 5,
            "story_rating": 5
          },
          "review_content_scores": {
            "content_quality": 80,
            "num_helpful_votes": 3,
            "num_unhelpful_votes": 0
          },
          "submission_date": "2019-08-28T13:36:45Z",
          "title": "Die restlichen Bücher von animox als hörbuch"
        }
      ],
      "customer_rights": null,
      "date_first_available": null,
      "distribution_rights_region": null,
      "editorial_reviews": null,
      "episode_count": null,
      "episode_number": null,
      "episode_type": null,
      "extended_product_description": null,
      "format_type": "abridged",
      "generic_keyword": null,
      "has_children": false,
      "image_url": null,
      "invites_remaining": null,
      "is_adult_product": true,
      "is_archived": null,
      "is_ayce": false,
      "is_buyable": null,
      "is_downloaded": false,
      "is_finished": null,
      "is_in_wishlist": null,
      "is_listenable": true,
      "is_pdf_url_available": null,
      "is_pending": false,
      "is_playable": null,
      "is_preorderable": null,
      "is_purchasability_suppressed": false,
      "is_removable": false,
      "is_removable_by_parent": true,
      "is_returnable": false,
      "is_searchable": null,
      "is_visible": null,
      "is_world_rights": null,
      "is_ws4v_companion_asin_owned": null,
      "is_ws4v_enabled": null,
      "isbn": null,
      "issue_date": "2017-10-23",
      "language": "german",
      "library_status": {
        "date_added": "2022-02-28T11:17:22.115Z",
        "is_pending": null,
        "is_preordered": null,
        "is_removable": false,
        "is_visible": null
      },
      "listening_status": null,
      "member_giving_status": null,
      "merchandising_description": null,
      "merchandising_summary": "Shark Alarm! Einfach abenteuerlich, was Simon und seine Freunde erleben. Diesmal führt es sie in die Tiefen des Pazifischen Ozeans...",
      "music_id": null,
      "narration_accent": null,
      "narrators": [
        {
          "asin": null,
          "name": "Peter Kaempfe"
        }
      ],
      "new_episode_added_date": null,
      "order_id": null,
      "order_item_id": null,
      "origin_asin": "B076KML76M",
      "origin_id": "D01-4653222-1874204",
      "origin_marketplace": "AN7V1F1VY261K",
      "origin_type": "Purchase",
      "part_number": null,
      "participation_plans": null,
      "pdf_url": null,
      "percent_complete": 0.0,
      "periodical_info": null,
      "plans": [],
      "platinum_keywords": null,
      "preorder_release_date": null,
      "preorder_status": null,
      "price": {
        "credit_price": 1.0,
        "is_buy_for_free_eligible": null,
        "is_credit_price_eligible": null,
        "is_free_eligible": null,
        "is_ws4v_upsell_eligible": null,
        "list_price": {
          "base": 11.949999809265137,
          "currency_code": "EUR",
          "merchant_id": "A3SGISXRF0LJBD",
          "type": "list"
        },
        "lowest_price": {
          "base": 4.949999809265137,
          "currency_code": "EUR",
          "merchant_id": "A3SGISXRF0LJBD",
          "type": "member"
        },
        "ws4v_upsell_price": {
          "base": 5.96999979019165,
          "currency_code": "EUR",
          "merchant_id": "A3SGISXRF0LJBD",
          "type": "ws4v_upsell"
        }
      },
      "product_images": {
        "500": "https://m.media-amazon.com/images/I/513a4TSR9JL._SL500_.jpg"
      },
      "product_page_url": null,
      "product_site_launch_date": null,
      "provided_review": null,
      "publication_name": "Animox",
      "publisher_name": "Oetinger Media",
      "publisher_summary": "Shark Alarm! <br /> <br />Einfach abenteuerlich, was Simon und seine Freunde erleben. Diesmal führt es sie in die Tiefen des Pazifischen Ozeans, in die Stadt der Haie! Hier suchen sie unter großen Gefahren das zweite Stück der mächtigen Waffe des Bestienkönigs, und sie finden deren wahren Ursprung und den Grund für ihre Zerstörung. Simon bekommt Zweifel: Ist es wirklich richtig, die Teile wieder zusammenzufügen? Oder bringt er sich und die ganze Welt von Animox damit in allergrößte Gefahr? <br /> <br />Neues Abenteuer aus der erfolgreichen Animox-Reihe. Mitreißend gelesen von Peter Kaempfe.",
      "purchase_date": "2022-02-28T11:17:22.115Z",
      "rating": {
        "num_reviews": 25,
        "overall_distribution": {
          "average_rating": 4.8277886497064575,
          "display_average_rating": "4.8",
          "display_stars": 5.0,
          "num_five_star_ratings": 440,
          "num_four_star_ratings": 56,
          "num_one_star_ratings": 1,
          "num_ratings": 511,
          "num_three_star_ratings": 14,
          "num_two_star_ratings": 0
        },
        "performance_distribution": {
          "average_rating": 4.7162471395881,
          "display_average_rating": "4.7",
          "display_stars": 4.5,
          "num_five_star_ratings": 341,
          "num_four_star_ratings": 75,
          "num_one_star_ratings": 3,
          "num_ratings": 437,
          "num_three_star_ratings": 17,
          "num_two_star_ratings": 1
        },
        "story_distribution": {
          "average_rating": 4.8223234624145785,
          "display_average_rating": "4.8",
          "display_stars": 5.0,
          "num_five_star_ratings": 376,
          "num_four_star_ratings": 50,
          "num_one_star_ratings": 1,
          "num_ratings": 439,
          "num_three_star_ratings": 12,
          "num_two_star_ratings": 0
        }
      },
      "read_along_support": null,
      "relationships": [
        {
          "asin": "B076H72GSL",
          "content_delivery_type": "BookSeries",
          "relationship_to_product": "parent",
          "relationship_type": "series",
          "sequence": "3",
          "sku": "SE_RIES_022126DE",
          "sku_lite": "SE_RIES_022126",
          "sort": "3",
          "title": "Animox",
          "url": "/pd/Animox-Hoerbuch/B076H72GSL"
        }
      ],
      "release_date": "2017-10-23",
      "review_status": null,
      "runtime_length_min": 284,
      "sample_url": "https://samples.audible.de/bk/oeti/000492/bk_oeti_000492_sample.mp3",
      "season_number": null,
      "series": [
        {
          "asin": "B076H72GSL",
          "sequence": "3",
          "title": "Animox",
          "url": "/pd/Animox-Hoerbuch/B076H72GSL"
        }
      ],
      "sku": "BK_OETI_000492DE",
      "sku_lite": "BK_OETI_000492",
      "social_media_images": {
        "facebook": "https://m.media-amazon.com/images/I/513a4TSR9JL._SL10_UR1600,800_CR200,50,1200,630_CLa%7C1200,630%7C513a4TSR9JL.jpg%7C0,0,1200,630+82,82,465,465_PJAdblSocialShare-Gradientoverlay-largeasin-0to70,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Large,TopLeft,600,270_OU01_ZBJETZT%20BEI,617,216,52,500,AudibleSansMd,30,255,255,255.jpg",
        "twitter": "https://m.media-amazon.com/images/I/513a4TSR9JL._SL10_UR1600,800_CR200,50,1024,512_CLa%7C1024,512%7C513a4TSR9JL.jpg%7C0,0,1024,512+67,67,376,376_PJAdblSocialShare-Gradientoverlay-twitter-largeasin-0to60,TopLeft,0,0_PJAdblSocialShare-AudibleLogo-Medium,TopLeft,490,223_OU01_ZBJETZT%20BEI,483,152,55,450,AudibleSansMd,32,255,255,255.jpg"
      },
      "status": "Active",
      "subscription_asins": null,
      "subtitle": "Animox 3",
      "text_to_speech": null,
      "thesaurus_subject_keywords": null,
      "title": "Stadt der Haie",
      "voice_description": null,
      "ws4v_companion_asin": null
    }
  ],
  "response_groups": [
    "claim_code_url",
    "sample",
    "is_downloaded",
    "percent_complete",
    "always-returned",
    "product_extended_attrs",
    "contributors",
    "product_plans",
    "series",
    "review_attrs",
    "product_plan_details",
    "pdf_url",
    "rating",
    "media",
    "product_attrs",
    "relationships",
    "product_desc",
    "provided_review",
    "reviews",
    "price",
    "origin_asin",
    "category_ladders",
    "badge_types",
    "is_returnable",
    "sku"
  ]
}

**Comment by audiamus** [comment]
Thank you. 

Before further investigation, this book is marked as `"is_adult_product": true`. Do you have "Adult products" enabled in the "Download settings"?

**Comment by Jasemat05** [comment]
In fact, I didn't had the option activated. Unfortunately, enabling the function didn't change anything, even after using the resync option.

**Comment by audiamus** [comment]
Do double-check: Once the "Adult products" check-box is on, the Library window will have a new column: "Adult". Like every other column, it's sortable. Click on the column header to sort by this column. A small triangular glyph will appear to indicate the sorting order. Scroll to the bottom and the top of the list to make sure the title really is not there. _Note: the list will try to keep the current position when sorting, so scrolling to the top or bottom afterwards is important._

Now, a "Resync" will download the meta data for the entire library again, but only add items to the local database that aren't there yet. Adult titles will always be added to the database, they are just filtered out for the library list if the check-box is not set.

What can go wrong when processing the Library Response JSON is that parts of the data cannot be interpreted correctly. This will normally throw an exception and the exception will be recorded in the log file. Can you upload the log file for a Book Lib Connect session during which you invoke the Resync command? Please zip it before uploading.

**Comment by Jasemat05** [comment]
Didn't help unfortunately.
Here is the log file.
[BookLibConnect_2022-03-06_005.zip](https://github.com/audiamus/BookLibConnect/files/8192737/BookLibConnect_2022-03-06_005.zip)

**Comment by audiamus** [comment]
Very strange. No exception in the log file. The log file says there is only one book in the response. That confirms what you said. The most unusual entry, however, is that 8 books are going to be removed. This looks like a bug. Are you using more than one profile? 

I have to test with the original response file in its condensed form. That should be easy as there is only one book in the file. Can you upload "LibraryResponse-2022_03_06-15_03_10.json" and "LibraryResponse-2022_03_06-15_03_37.json"? As a zip again, please.  

You can also try something else on your side but I don't really expect any change: Start with a fresh database. Save the current database by renaming it or moving it. It's SQLite, so it's a single file located here: `C:\Users\<USER>\AppData\Local\audiamus\BookLibConnect\data\audiobooks.db`. If this file does not exist, Book Lib Connect will create a new database and populate it from scratch.

**Comment by Jasemat05** [comment]
The title is showing!!!!
The change of the database file was the solution.
Thank you very much!!!

**Comment by audiamus** [comment]
That's good to hear.

Can you still upload  "LibraryResponse-2022_03_06-15_03_10.json" and "LibraryResponse-2022_03_06-15_03_37.json" (as a zip)? I would try to reproduce this obscure behaviour.

**Comment by Jasemat05** [comment]
Here are the files.
[LibraryResponse-2022_03_06-15_03_37.zip](https://github.com/audiamus/BookLibConnect/files/8203363/LibraryResponse-2022_03_06-15_03_37.zip)

**Comment by audiamus** [comment]
Perfect, thanks a lot. It will be a few days before I'll find the time to do the testing but will report back once I have some result.
