### ISSUE TITLE
File name is not correct

### ISSUE THREAD

**Issue by lukethehawk** [audiamus/BookLibConnect#32]
Hi, thank you for your work, 
all the files coverted in m4b have the name troncated and concatenated to other infos
Is possible to download the file with the full correct name?

Example:
Sherlock Holmes e un caso d'identità -> Sherlock Holmes e un_B01BY27G9K_LC_128_44100.m4b

thank you

**Comment by audiamus** [comment]
The file name composition is the same as with the official Audible Win 10 app. To obtain proper file names, sorted by author, or even by series, run [AAX Audio Converter](https://github.com/audiamus/AaxAudioConverter) afterwards. There you have plenty of options.

_Keep in mind that Book Lib Connect will eventually become an integrated component of AAX Audio Converter._

**Comment by lukethehawk** [comment]
Ok I will use AAX Audio Converter for this purpose. Thank you
