### ISSUE TITLE
 Problem mit den Kapitelnamen bei MP3 Umwandlung von Booklibconnect Download von  Stepehen King the Stand 

### ISSUE THREAD

**Issue by alurio** [audiamus/BookLibConnect#33]
Hey Audiamus, 

Habe gerade The Stand von Stepehen King via Booklib Connect runtergeladen und wollte es dann, wie immer mit AAX Audiokoncerter in Mp3 übersetzen lassen. 

Seltsamerweise werden die Kapitelnamen nicht übernommen obwohldie entsprechende option im AAX Audiokonverter aktiv ist,  Booklibconnect die üblichen Metadaten  liefert und die Kapitel auch korrekt in der  ja als Vorlage für die pseudo AAX dienenden M4b stehen. ( Laut Mediainfo.) Eigentlich müsste also alles klappen, tuts aber nicht. 

Ich weiß jetzt nicht welches programm den Fehler macht, ob Booklib oder  AAX Converter, jedenfalls geht hier irgendwas schief. 

Vielleicht liegt es daran, dass das Buch sehr lang ist ( 53 Stunden ) 

Ich hänge mal sämtliche Metadaten als Zip an, vielleicht hast du ne Idee 
[Metadata_The Stand .zip](https://github.com/audiamus/BookLibConnect/files/8277390/Metadata_The.Stand.zip)

viele Grüße

**Comment by audiamus** [comment]
Das sieht von den JSON-Metadaten her in der Tat unverdächtig aus. Da muss man mal einen Blick ins Log von AAX Audio Converter werfen, Log Level 3 reicht.

Es ist aber durchaus denkbar, dass wir bei sehr langen Büchern an Grenzen stoßen.

**Comment by alurio** [comment]
Hallo Audiamus, 
Hab das Buch mit Level 3 durchlaufen lassen, Das Text File sieht erstmal korrekt aus. Die Namen der Kapitel stehen drin. Aus irgend einem Grund werden sie aber eben nicht  in die Dateien übernommen. Stattdessen gibt es nur  MP3 01 -88 was bis auf die fehlenden Namen auch  Korrekt ist. Die Buchstruktur wird also richtig erfasst.
Naja ich hänge die Datei mal an. Vielleicht findest du ja heraus woran es liegt und kannst das mit einem kleinen Update beheben. 

[AaxAudioConverter_2022-03-17_The Stand.zip](https://github.com/audiamus/BookLibConnect/files/8284433/AaxAudioConverter_2022-03-17_The.Stand.zip)

Viele Grüße

**Comment by audiamus** [comment]
Danke. Sieht nach Fehler aus: Integer Overflow beim Lesen der Json-Kapiteldaten. Dann wird die Datei ignoriert. Und bei den eingebetteten Kapiteldaten wird der Kapiteltitel grundsätzlich ignoriert, weil dort bis vor Kurzem immer nur durchgezählt wurde.

Mögliche Abhilfe: Ein derart langes Buch wird doch vermutlich auch als mehrteiliger Download zur Verfügung stehen, was Book Lib Connect ja unterstützt. Und wenn Du eh für MP3 in Kapitel aufspaltest, dann spielt es ja keien Rolle, ob die ursprüngliche Quelle aus einer oder mehreren Dateien bestand.

**Comment by alurio** [comment]
Hey Audiamus, 

selbstverständlich gibt es solche Schinken auch Mehrteilig. 
Ich teste es gerade bei  mehrteiligem Download  funktionieren die Kapitelnamen 
Ich würde das aber wo immer möglich gerne vermeiden, denn das  einteilige Konvertieren erspart mir die Extra Arbeit die willkommen bei Audible Ansage am Beginn jedes Teils raus zu schneiden bzw die Extra Kapitel zu löschen  die die Ansage enthalten  und die so veränderten Dateien  händisch  mit Metadaten  zu versehen.  und zu nummerieren. Das Automatische Ausfiltern funktioniert nämlich meistens nicht. 
Aus 88 Kapiteln sind hier jetzt 94 geworden. 
Insofern wäre es klasse wenn sich dieser Overflow bei langen Büchern  abfangen ließe. 

Wenn nicht ist das aber  natürlich auch keine Katastrophe dann bastele ich halt. 


Viele Grüße

**Comment by audiamus** [comment]
Das kommt dann schon heute Abend auf die Todo-Liste. In Book Lib Connect ist dieses Feld auch bereits als long definiert. Ist übrigens die gleiche Ursache, die bei AAXClean für die falsche Kapitelreihenfolge sorgte.

Was mich wundert ist, dass die Übergänge zwischen den Teilen nicht herausgefiltert werden. Auch hier hängt der Erfolg zumindest partiell wieder von den Metadaten ab. Aber wenn es in der content_meta richtig steht, dann sollte es wirken. Allerdings hast Du in Deinen Einstellungen laut Log die Zeitspanne für die "sehr kurzen Kapitel" auf 0 gesetzt. Die Voreinstellung ist 10. Damit bekommt man dann "This is Audible" und "Audible hopes you have enjoyed this programme" zu hören oder eben nicht. Die offizielle Win10-App hat das ja interessanterweise auch immer weggefiltert.

**Comment by alurio** [comment]
Ah Okay Ich dachte immer entscheidend für das filtern von Hallo hier ist Audible ist der menüpunkt kurze Kapitel zwischen Buchteilen überspringen. Den hab ich auf 25 Sekunden. bei The Stand würde kurze Kapitel überspringen aber mutmaßlich nix helfen. Die Willkommen bei Audible Ansage ist nämlich kein eigenes mini Kapitel sondern ist jeweils Teil eines mehre Minuten langen Kapitels. 
Aber ich spiel das mal durch. 

Viele grüße

**Comment by alurio** [comment]
Oh Spannend, der Converter ist tatsächlich in der Lage Wilkommen bei Audible zu filtern, ohne die kleinen zwischen Kapitel zu streichen. Und er nimmt sogar das Willkommen bei Audible am Buchanfang weg. Finde ich zwar nicht nötig aber nett.

**Comment by audiamus** [comment]
Es kann sein, dass da eine gegenseitige Abhängigkeit besteht, zwischen den Filtern "kurz" und "sehr kurz". War allerdings nicht beabsichtigt. Ich hab's ebenfalls notiert.

> entstehen hier jetzt falsch benannte mini Kapitel ein Teil von Kapitel 35 ist im Kapitel Buch 1 Captain Trips, das es mehrfach gibt verschoben. 

Was halt passieren kann ist, dass Audible ein Kapitel zwischen zwei Buchteilen trennt. Dann sollten aber zumindest die eingebetteten Titel (Tags) weiterhin korrekt sein. Wenn Du mir nochmal ein Log zur Verfügung stellst, kann ich nachschauen, wie es gehandhabt wurde.

**Comment by audiamus** [comment]
Danke. Ich schaue es mir morgen noch gründlicher an, habe aber schon eine Idee. Vielleicht könnte man diese Fälle in Book Lib Connect beim Export abfangen. Das sieht nämlich so aus, als ob es die Folge einer hierarchischen Kapitelstruktur ist. Mein Ziel ist auf  jeden Fall, mehrteilige Downloads so kompatibel wie möglich zu machen.

**Comment by alurio** [comment]
Hey Audiamus, 
vielen Dank, wäre topp wenn sich da eine Lösung findet, ich werde mal testweise Fundament der Ewigkeit in einem Stück laden. Das sind 10  Teile und 37  Stunden.  Mich interessiert jetzt bei welcher Länge die Kapitel Namen aussteigen.. 

Viele Grüße

**Comment by alurio** [comment]
Hey, 

Das Problem ist reproduzierbar, auch bei Fundament der Ewigkeit kommen die Kapitelnamen nicht mit obwohl sie ausgewählt sind im Log stehen und auch Korrekt in der M4B aufgeführt sind Damit bestätigt sich nach meinem Verständnis  das etwas beim Export und der anschließenden Transkodierung nicht funktioniert ( Overflow ) 

Hier zu Analysezwecken die Audible Metadaten und  der Log. 

 [Metadaten und Log Fundament der Ewigkeit.zip](https://github.com/audiamus/BookLibConnect/files/8292568/Metadaten.und.Log.Fundament.der.Ewigkeit.zip)

Viele Grüße

**Comment by audiamus** [comment]
Ja, bei `content_size_in_bytes` fliegt er raus, ab Dateigröße 2GB. Das ist wie gesagt in Book Lib Connect schon eine 64bit-Integer (sonst könnte die Datei gar nicht erst erzeugt werden), aber in AAX Audio Converter noch 32bit. Da beim Einlesen aber nur die ganze JSON-Datei betrachtet wird, und nicht einzelne Werte, kann sie dann insgesamt nicht gelesen werden. 

Interessant ist auch bei diesem Buch wieder, dass die externen Kapiteldaten ein wenig freundlicher gestaltet sind als die internen., z.B. "Teil 2: 1559 - 1563" statt nur "1559 - 1563".

Es wird wohl so aussehen, dass ich Book Lib Connect zuerst aktualisiere, danach AAX Audio Converter, weil dort noch anderes zu tun ist, auch in Vorbereitung auf die Integration der beiden Tools, was aber noch dauern wird.

**Comment by alurio** [comment]
Hallo Audiamus , 

Okay dann warte ich gespannt auf die  Aktualisierungen. Würde ein Austausch der ffmpeg Version  im AAX Audioconverter als zeitweiliger Workaround taugen ? oder ist das nicht entscheidend für das Problem ? 

Viele Grüße

**Comment by audiamus** [comment]
> Würde ein Austausch der ffmpeg Version im AAX Audioconverter als zeitweiliger Workaround taugen ?

Nein, FFmpeg ist hier nicht betroffen.

**Comment by alurio** [comment]
Schade, Na gut dann freue ich mich wie gesagt auf die nächsten  Versionen von Booklib und AAX Audiokonverter, die das Problem dann lösen und hoffe es dauert nicht so lange. 

Aber über 2 GB Große Schinken hat man ja nicht ständig also ist es auch kein riesending  etwas zu warten. 

Viele Grüße

**Comment by audiamus** [comment]
Die Sache ist doch nicht so einfach. Könntest Du mir von den beiden Mehrteilern jeweils alle LicenseResponse.json zur Verfügung stellen? Die Kapitelzeiten der einzelnen Teile sehen in der flachgeklopften Version irgendwie komisch aus.

**Comment by alurio** [comment]
Das heißt ich  soll die mehrteiler in Teilen laden und dann die License respomnse schicken ? oder in einem stück ? 

Grüß

**Comment by audiamus** [comment]
Genau, als mehrteilig herunterladen. Dann gibt es je Teil eine eigene LicenseResponse.json mit jeweils eigener, in diesem Fall hierarchischer, Kapitelstruktur.  Ich habe den Verdacht, dass beim jeweils nächsten _physikalischen_ Teil die hierarchische Kapitelstruktur für die _logischen_ Teile dann, wenn der _logische_ Teil noch fortgesetzt werden muss, anderen, noch unbekannten  Regeln folgt.

**Comment by alurio** [comment]
Okay ist in Arbeit 
Möchtest du zum Vergleich auch noch die json Response des Downloads in einem Stück  oder ist das nicht nötig ? 

grüße

**Comment by audiamus** [comment]
Ja, vielleicht. Könntest Du sicherheitshalber dazu packen. Danke.

**Comment by alurio** [comment]
Hallo ! 
Hier sind die Daten The stand und Fundament der Ewigkeit Licewnse Response  Dateien jeweils in Teilen und  am Stück 

Viel Erfolg bei der Analyse 

Viele grüße 


1. The Stand mehrteilig 
[The stand License response mehrteilig .zip](https://github.com/audiamus/BookLibConnect/files/8311100/The.stand.License.response.mehrteilig.zip)

2. Fundament der Ewigkeit mehrteilig 
[License Response Fundament der Ewigkeit in Teilen .zip](https://github.com/audiamus/BookLibConnect/files/8311119/License.Response.Fundament.der.Ewigkeit.in.Teilen.zip)
 
3. The Stand an einem Stück 
[LicenseResponse_The Stand an einem Stück.zip](https://github.com/audiamus/BookLibConnect/files/8311160/LicenseResponse_The.Stand.an.einem.Stuck.zip)

4 Fundament der Ewigkeit am Stück 
[Fundament der Ewigkeit am Stück .zip](https://github.com/audiamus/BookLibConnect/files/8311195/Fundament.der.Ewigkeit.am.Stuck.zip)

**Comment by audiamus** [comment]
Ich danke Dir. Ein erster Blick bestätigt die merkwürdigen Zeitangaben bei den Mehrteilern. Daher ist es in der Tat sehr hilfreich, auch die Struktur beim ungeteilten Buch sehen zu können. Mal schauen, ob ich die Logik dahinter entziffern kann.

**Comment by alurio** [comment]
Gern geschehen, 
es macht mir Spaß bei der Weiterentwicklung der beiden Programme zu helfen. 

Ich hoffe du löst das Rätsel und  machst auch sehr Lange Bucher am Stuck geladen vollständig nutzbar, inklusive Kapitelnamen. 

Aber ich bin da sehr Optimistisch. Bisher hast du ja noch für jedes Problem früher oder später eine Lösung gefunden. 
Viele Grüße

**Comment by audiamus** [comment]
Ich hätte erwartet, dass im jeweils nächsten physikalischen Teil der logische Teil erneut angesagt wird und das nächste Kapitel oder oder Fortsetzung des bisherigen Kapitels folgt.

Ich sehe aber bei Beginn des nächsten Teils ein sehr viel längeres Kapitel.

Beispiel aus "The Stand":

Mehrteilig,
Teil 1:
```
                           {
                                "length_ms": 1045204,
                                "start_offset_ms": 22761449,
                                "start_offset_sec": 22761,
                                "title": "Kapitel 17"
                            },
                            {
                                "length_ms": 2809684,
                                "start_offset_ms": 23806653,
                                "start_offset_sec": 23807,
                                "title": "Kapitel 18"
                            }
                        ],
                        "length_ms": 44000,
                        "start_offset_ms": 1768362,
                        "start_offset_sec": 1768,
                        "title": "Buch eins: Captain Trips"
```
Teil 2:
```
                             {
                                "length_ms": 1221462,
                                "start_offset_ms": 367224,
                                "start_offset_sec": 367,
                                "title": "Kapitel 19"
                            },
                            {
                                "length_ms": 1482131,
                                "start_offset_ms": 1588686,
                                "start_offset_sec": 1589,
                                "title": "Kapitel 20"
                            },
...
                       ],
                        "length_ms": 367224,
                        "start_offset_ms": 0,
                        "start_offset_sec": 0,
                        "title": "Buch eins: Captain Trips"
```
Einteilig:
```
                            {
                                "length_ms": 1045204,
                                "start_offset_ms": 22761449,
                                "start_offset_sec": 22761,
                                "title": "Kapitel 17"
                            },
                            {
                                "length_ms": 3172728,
                                "start_offset_ms": 23806653,
                                "start_offset_sec": 23807,
                                "title": "Kapitel 18"
                            },
                            {
                                "length_ms": 1221462,
                                "start_offset_ms": 26979381,
                                "start_offset_sec": 26979,
                                "title": "Kapitel 19"
                            },
                            {
                                "length_ms": 1482131,
                                "start_offset_ms": 28200843,
                                "start_offset_sec": 28201,
                                "title": "Kapitel 20"
                            },
...
                        ],
                        "length_ms": 44000,
                        "start_offset_ms": 1768362,
                        "start_offset_sec": 1768,
                        "title": "Buch eins: Captain Trips"
``` 

Die Teil-Überschrift "Buch eins: Captain Trips" dauert in der einteiligen Datei 44 sec (auch schon recht lang). Ebenso im physikalischen Teil 1. Im physik. Teil 2 aber 367 sec. Kapitel 18 dauert einteilig 3173 sec, im Teil 1 aber nur 2810 sec. Also wird im physik. Teil 2 Kapitel 18 wohl fortgesetzt. Das ist aber in den Kapiteldaten nicht mehr unterteilt. Die Differenz ist 363 sec. Bleiben 4 sec mit unbekanntem Inhalt. Frage: Was erzählt der Sprecher in den ersten Sekunden im Teil 2, bevor es mit Kapitel 18 weitergeht? Kommt da "This is Audible" (soll, 4.2 sec dauern)? Kamm man mit den M4B-Dateien herausfinden, die ja unverändert aus den AAXC-Dateien entstehen.

**Comment by alurio** [comment]
Hallo Audiamus, 

Also ich kann bestätigen das Kapitel 18 im 2. Teil einfach fortgesetzt wird ( unter dem Namen  Teil 1 Captain Trips) Man muss dann also um ein komplettes 18 Kapitel zu haben beides zusammenfügen. Die vier Sekunden sind höchstwahrscheinlich die 
 willkommen bei Audible Ansage,  ich überprüfe das ( Muss die Daten dafür allerdings nochmal Laden, dauert also ein bisschen. Melde  mich dann gleich.

**Comment by alurio** [comment]
Ja, richtig vermutet die 4-5  Sekunden  mit unbekanntem Inhalt bzw differenz entfallen auf die Willkommen bei Audible Ansage . Ist dann ein  Muster, andere Teile  fangen ja dann auch mit Teil so und so an und setzen dass vorhergehende Kapitel fort. 
Viele Grüße

**Comment by alurio** [comment]
Book Lib connect hat gerade einen Unbehandelten Ausnahmefahler produziert. Lies sich zwar weg klicken, und es liegen auch aklle axt m4bs vor aber  da  er das normalerweise nicht macht, hab ich die fehlermeldung mal in ein text kopiert 


bitte sehr 
[Fehlermeldung booklibconnect .txt](https://github.com/audiamus/BookLibConnect/files/8318629/Fehlermeldung.booklibconnect.txt)

**Comment by alurio** [comment]
Wenn ich mich nicht völlig irre ist es bei Fundament der Ewigkeit genauso, auch da werden am Beginn eines Downloadteils Kapitel unter dem Namen einer Zwischenüberschrift fortgesetzt inklusive  Wilkommen bei Audible Ansage. Bei 10b Download Parts war da schon einiges an Bastelei nötig.

**Comment by audiamus** [comment]
> Book Lib connect hat gerade einen Unbehandelten Ausnahmefahler produziert.

Sieht sehr nach #34 aus. Ist das auch bei Dir ein Dateiname mit Umlaut? Es wird bei dieser Kopieraktion direkt auf die Win32-Schnittstelle zugegriffen, für höchste Transferleistung, und da scheint es so zu sein, dass die Dateinamen nicht automatisch als Unicode interpretiert oder angelegt werden.

**Comment by audiamus** [comment]
> Ja, richtig vermutet die, wenn man sehr rough schneidet 4,2 Sekunden mit unbekanntem Inhalt bzw Differenz entfallen auf die Willkommen bei Audible Ansage . 

Das ist schlecht. Denn dann habe ich keine Chance mit meiner Idee der Unterdrückung, wenn die Kapiteldaten nicht mit dem Inhalt überein stimmen.    

Ich werde dieses Filter trotzdem einbauen, auch wenn es bei diesen beiden Beispielen nicht greifen wird.

**Comment by alurio** [comment]
Ne Die Dateien heißen ja nur The Stand 1-8 Also  keine Umlaute. Vielleicht hat aber ein Kapitel innerhalb der M4B  einen Umlaut, dass weiß ich nicht.

**Comment by alurio** [comment]
> > Ja, richtig vermutet die, wenn man sehr rough schneidet 4,2 Sekunden mit unbekanntem Inhalt bzw Differenz entfallen auf die Willkommen bei Audible Ansage .
> 
> Das ist schlecht. Denn dann habe ich keine Chance mit meiner Idee der Unterdrückung, wenn die Kapiteldaten nicht mit dem Inhalt überein stimmen.
> 
> Ich werde dieses Filter trotzdem einbauen, auch wenn es bei diesen beiden Beispielen nicht greifen wird.

 Hmm Aber AAX Audiokonverter kann das ja filtern,  vosusgesetzt sehr kurze Kapitel ist als Option aktiviert hilft das nicht ?
Außerdem ist das Ziel doch eigentlich dass er den einteiligen Download korrekt verarbeitet. Mit denen gibt es dann ja auch keine  Zwischenansagen.

**Comment by alurio** [comment]
Eigentlich  muss ja " nur " verhindert werden daß der Konverter ab 2 GB Größe  aussteigt und die Metadaten deshalb ignoriert in der M4B der einteiligen Downloads sind ja alle Kapitel und Namen korrekt.

**Comment by audiamus** [comment]
> Ne Die Dateien heißen ja nur The Stand 1-8 Also keine Umlaute. Vielleicht hat aber ein Kapitel innerhalb der M4B einen Umlaut, dass weiß ich nicht.

Es könnte auch sein, dass die M4B-Datei noch geöffnet war (Player?). Das führt bislang ebenfalls zum Fehler, der aber bisher nicht korrekt abgefangen wurde. 

Wird gefixt.

**Comment by alurio** [comment]
> > Eigentlich muss ja " nur " verhindert werden daß der Konverter ab 2 GB Größe aussteigt und die Metadaten deshalb ignoriert in der M4B der einteiligen Downloads sind ja alle Kapitel und Namen korrekt.
> 
> Das wird ja kommen. Ist an sich eine Kleinigkeit, nur ist AAX Audio Converter im Moment eine Baustelle, und die anderen Baugruben müssen erst wieder verfüllt werden.

Na dann ist eine Lösung ja absehbar und die  abweichenden Kapitelzeiten bei komisch geteilten Büchern sind dann auch kein Problem für die Ewigkeit. Super ! 

Die Ausfilterung der Willkommen bei Audible Ansage funktioniert übrigens hervorragend.( jetzt wo ich weiß welche Einstellung dafür entscheidend ist)  Hatbeim aktuellen Problem  den Vorteil das man  das begonnen Kapitel und seine Fortsetzung unter falschem Namen sehr gut zusammenschieben kann, ohne nochmal Hand ans Audio legen zu müssen, bzw wenn die Nummerierung einfach nur Kapitel 1,2,3 und so weiter ist werden sehr zuverlässig genau  die 3-4 Sekunden Ansage gekürzt. 

 
 
> > Ne Die Dateien heißen ja nur The Stand 1-8 Also keine Umlaute. Vielleicht hat aber ein Kapitel innerhalb der M4B einen Umlaut, dass weiß ich nicht.
> 
> Es könnte auch sein, dass die M4B-Datei noch geöffnet war (Player?). Das führt bislang ebenfalls zum Fehler, der aber bisher nicht korrekt abgefangen wurde.
> 
Durchaus Möglich das VLC noch offen war 
> Wird gefixt.
wunderbar 

Viele Grüße

**Comment by audiamus** [comment]
In [Version 0.6](https://github.com/audiamus/BookLibConnect/releases/tag/v0.6) gibt es die neue Behandlung von sich wiederholenden Kurzkapiteln. Wird aber, wie hier diskutiert, bei Deinen Beispielen keine Änderung bringen. 

_(Integer Overflow in AAX Audio Converter weiterhin in der Pipeline.)_

**Comment by alurio** [comment]
Ich installiere trotzdem die neue Version und warte ab bisder integer Overflow in AAX Audio Converter  die Pipeline verlässt . 

Grüße

**Comment by alurio** [comment]
> In [Version 0.6](https://github.com/audiamus/BookLibConnect/releases/tag/v0.6) gibt es die neue Behandlung von sich wiederholenden Kurzkapiteln. Wird aber, wie hier diskutiert, bei Deinen Beispielen keine Änderung bringen.
> 
> _(Integer Overflow in AAX Audio Converter weiterhin in der Pipeline.)_

Ist das mit dem Integer Overflow denn eher eine Frage von Tagen, Wochen oder Monaten ?
