### ISSUE TITLE
Downloads don't start

### ISSUE THREAD

**Issue by jimwhitfield** [audiamus/BookLibConnect#38]
Hi Thanks so much for this.
I got all the way to having the list of my titles from audible.
I add them to the download list (falling back to just one, the most recent) 
When I leave the "Library for" window, nothing happens on the main panel.
I went back into [Download] ("Library for..") and pressed Resync.  nothing happens.
This even happens now that I run it as an administrator from the CMD box.  (i get no warning/errors as the program runs detached from the shell)
C:\Users\jim\Music\Audible>"\Program Files\audiamus\Book Lib Connect\BookLibConnect.exe"
C:\Users\jim\Music\Audible>

Thanks for any insight

**Comment by audiamus** [comment]
- In the Library window you have the list of your books. Select one or more in that list with the mouse. 
- At the top of the Library window, the [Add selected] button will now be enabled. Click [Add Selected]. The selected books will now appear in the list of the main window. The icon for the selected books will change to a mauve down arrow in a black circle.
- In the main window the books just added from Library window will be selected by default. The [Run] button will become enabled.
- Click the [Run] button to start the process. 

If the app behaves differently on your system, please upload the log file here (in zipped format).

**Comment by jimwhitfield** [comment]
ok, thanks.  I didn't see a visual indication that the Run button was enabled, and could swear that I tried clicking it before, but indeed that was the magic.  Thanks so much.
