### ISSUE TITLE
DotNet SDK needed for Windows X64 binary to run

### ISSUE THREAD

**Issue by aweussom** [audiamus/BookLibConnect#39]
You should link to this:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.407-windows-x64-installer

**Comment by audiamus** [comment]
I'm afraid that's beyond my control. The app will point to a download page that Windows reckons to be suitable.

**Comment by audiamus** [comment]
The SDK is not required.

The .Net 5 download page is : https://dotnet.microsoft.com/en-us/download/dotnet/5.0

You will need .NET Desktop Runtime 5.0.*, emphasize: **Desktop**, for Windows x64.

At the time of writing this is 5.0.16. 

The direct link for that is: 
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.16-windows-x64-installer

**Comment by aweussom** [comment]
I can assure you that the program would NOT run until I installed the SDK.
The runtime alone was NOT enough.

It may be just my laptop; Running Windows 11.

**Comment by audiamus** [comment]
The important thing is to install the **Windows Desktop** version of the runtime, not the ordinary runtime or the ASP.Net Core runtime. SDK stands for "System **Development** Kit". It contains all the runtimes plus the development tools like the compiler, debugger support and a number of utilities. None of the development tools is needed to run a .Net app.

**Comment by aweussom** [comment]
Ok. I installed the one that was suggested in the app popup when it failed to start.
I probably selected the wrong version then :-)
