### ISSUE TITLE
sqlite Error

### ISSUE THREAD

**Issue by msebastian100** [audiamus/BookLibConnect#45]
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Books.Asin'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Private.CoreLib.dll.
----------------------------------------
BookLibConnect
    Assembly-Version: 0.8.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.dll.
----------------------------------------
audiamus.aux.core
    Assembly-Version: 2.1.0.1.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 5.0.16.0.
    Win32-Version: 5.0.1622.16805.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 5.0.16.0.
    Win32-Version: 5.0.1622.16805.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/System.Windows.Forms.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Collections.Specialized.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ComponentModel.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 5.0.0.2.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Collections.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Text.RegularExpressions.dll.
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.InteropServices.RuntimeInformation.dll.
----------------------------------------
System.Memory
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Memory.dll.
----------------------------------------
System.IO.FileSystem
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.IO.FileSystem.dll.
----------------------------------------
System.Text.Json
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Text.Json.dll.
----------------------------------------
System.Text.Encodings.Web
    Assembly-Version: 5.0.0.1.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Text.Encodings.Web.dll.
----------------------------------------
System.Runtime.Intrinsics
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.Intrinsics.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Collections.Concurrent.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Private.Uri.dll.
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Primitives.dll.
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Emit.Lightweight.dll.
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Emit.ILGeneration.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Numerics.Vectors.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Threading.Thread.dll.
----------------------------------------
System.Linq
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Linq.dll.
----------------------------------------
System.Console
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Console.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Text.Encoding.Extensions.dll.
----------------------------------------
audiamus.connect.core
    Assembly-Version: 0.8.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.aux.win.core
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.common.util.core
    Assembly-Version: 0.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.booksdb.core
    Assembly-Version: 0.5.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.connect.ui.core
    Assembly-Version: 0.8.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.1622.16805.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/Accessibility.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ComponentModel.TypeConverter.dll.
----------------------------------------
audiamus.common.types.core
    Assembly-Version: 0.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 5.0.16.0.
    Win32-Version: 5.0.1622.16805.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.Extensions.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
audiamus.aux.propgrid.core
    Assembly-Version: 0.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/System.Resources.Extensions.dll.
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/netstandard.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 5.0.16.0.
    Win32-Version: 5.0.1622.16805.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.16/System.Drawing.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ObjectModel.dll.
----------------------------------------
System.Buffers
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Buffers.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Collections.NonGeneric.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Threading.ThreadPool.dll.
----------------------------------------
audiamus.aux.treedecomp.core
    Assembly-Version: 2.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Http
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.Http.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.Primitives.dll.
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Diagnostics.Tracing.dll.
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Security
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.Security.dll.
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Cryptography.X509Certificates.dll.
----------------------------------------
System.Net.Sockets
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.Sockets.dll.
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.NameResolution.dll.
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Threading.Overlapped.dll.
----------------------------------------
audiamus.sysmgmt.core
    Assembly-Version: 1.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/Microsoft.Win32.Registry.dll.
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.Serialization.Formatters.dll.
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Cryptography.Algorithms.dll.
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Cryptography.Primitives.dll.
----------------------------------------
Microsoft.EntityFrameworkCore
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly-Version: 5.0.0.1.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Linq.Expressions.dll.
----------------------------------------
Microsoft.EntityFrameworkCore.Abstractions
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Private.CoreLib.dll.
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Data.Common
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Data.Common.dll.
----------------------------------------
System.Transactions.Local
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Transactions.Local.dll.
----------------------------------------
Microsoft.Extensions.Logging
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Annotations
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.ComponentModel.Annotations.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Collections.Immutable.dll.
----------------------------------------
System.Net.NetworkInformation
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Net.NetworkInformation.dll.
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Principal.Windows.dll.
----------------------------------------
System.Security.Claims
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Claims.dll.
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly-Version: 5.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Data.Sqlite
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly-Version: 2.0.4.976.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    Assembly-Version: 2.0.4.976.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.core
    Assembly-Version: 2.0.4.976.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.nativelibrary
    Assembly-Version: 2.0.4.976.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.EntityFrameworkCore.Proxies
    Assembly-Version: 5.0.11.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Castle.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.dll.
----------------------------------------
System.Reflection.TypeExtensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.TypeExtensions.dll.
----------------------------------------
System.Reflection.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Extensions.dll.
----------------------------------------
System.Reflection.Emit
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Emit.dll.
----------------------------------------
DynamicProxyGenAssembly2
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: file:///C:/Program%20Files/audiamus/Book%20Lib%20Connect/Castle.Core.dll.
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.Serialization.Primitives.dll.
----------------------------------------
DynamicProxyGenAssembly2
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: file:///C:/Program%20Files/audiamus/Book%20Lib%20Connect/Castle.Core.dll.
----------------------------------------
System.Linq.Queryable
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Linq.Queryable.dll.
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Security.Cryptography.Encoding.dll.
----------------------------------------
audiamus.audiible.json.core
    Assembly-Version: 0.4.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Private.Xml.dll.
----------------------------------------
System.Formats.Asn1
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Formats.Asn1.dll.
----------------------------------------
System.Runtime.Numerics
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Runtime.Numerics.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.1622.16705.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.16/System.Reflection.Metadata.dll.
----------------------------------------

************** JIT-Debuggen **************

**Comment by audiamus** [comment]
Kannst Du die Log-Datei dazu mit hochladen?
