### ISSUE TITLE
Not able to login with with the provided link

### ISSUE THREAD

**Issue by nguyenxndaidev** [audiamus/BookLibConnect#50]
![image](https://user-images.githubusercontent.com/24372782/174432568-c8cb3b00-bc5e-4860-ac14-8a0abbc7b521.png)

![image](https://user-images.githubusercontent.com/24372782/174432597-b0acf425-985f-4304-9df4-95f23c09865e.png)

**Comment by mkb79** [comment]
@nguyenxndaidev 
Do you have select to login with a pre-Amazon Audible account in Germany. Do you have such account?

**Comment by nguyenxndaidev** [comment]
@mkb79 oh, I think I misunderstood the meaning of the checkbox. Deselect the checkbox will work.
Well, btw, when do we need to select this checkbox? I created my Audible account from my Amazon Prime Account.

**Comment by mkb79** [comment]
@nguyenxndaidev 
> Well, btw, when do we need to select this checkbox? I created my Audible account from my Amazon Prime Account.

As Amazon has purchased Audible in 2008, all new members had to register with an Amazon account. But old Audible accounts are not ported to an Amazon account (this was and is optional)! Since then, there are two different types of login.
