### ISSUE TITLE
.NET Runtime 5.0.17 not recognized

### ISSUE THREAD

**Issue by IamKayrox** [audiamus/BookLibConnect#52]
.NET Runtime 5.0.17 is not recognized, the pop up to download .NET Runtime still appears and the version 5.0.0 seems to not be available anymore.

**Comment by audiamus** [comment]
.NET Runtime 5.0.17 for x64 may be out of support but is still available, of course, same place as before:
https://dotnet.microsoft.com/en-us/download/dotnet/5.0
Direct link:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer

_I have to say that the short lifetime of .Net 5 surprised me a little. Naturally, I will update Book Lib Connect to .Net 6 some time soon_

**Comment by IamKayrox** [comment]
That's the curious thing, message still pop ups even though I installed it.
Maybe I'm missing something else?

**Comment by audiamus** [comment]
Did you install from my direct link?

**Comment by IamKayrox** [comment]
Sorry for the delay, I installed the desktop variant, the x64 and x86. Rebooted my computer and yet nothing.

**Comment by audiamus** [comment]
Yep. If unsure what you have installed, open a command prompt ("cmd" in the Windows Start menu) and enter 
`dotnet --list-runtimes`
This will list all the installed runtimes of the .Net Core family of products.
