### ISSUE TITLE
Program Doesn't Work

### ISSUE THREAD

**Issue by Lagunabel** [audiamus/BookLibConnect#54]
Please, can you help me?

![5](https://user-images.githubusercontent.com/92586781/177314956-761d9bfd-d162-4765-94ca-92611f3a4920.jpg)

**Comment by audiamus** [comment]
I believe this is related to #53. Please have a bit of patience. I will look into this soon, hopefully in the coming days.

**Comment by audiamus** [comment]
Version 0.9 has just been released, with improved handling of incomplete Audible API responses.

**Comment by Lagunabel** [comment]
I downloaded the latest version and finally work! Thank you so much for your great programs! 🤩🥳
