### ISSUE TITLE
Can't see library for any accounts

### ISSUE THREAD

**Issue by RyanU1328** [audiamus/BookLibConnect#55]
I logged in okay with a UK and US account. However, my library doesn't show up and most of the options are greyed out. Any advice?

![image](https://user-images.githubusercontent.com/86496134/177353223-2fed9fcc-57e2-48e4-b118-e26cc098992c.png)

**Comment by RyanU1328** [comment]
I should note I have left it for a while in the hope it would populate my library

**Comment by audiamus** [comment]
I believe this is related to #53. Please have a bit of patience. I will look into this soon, hopefully in the coming days.

**Comment by audiamus** [comment]
Version 0.9 has just been released, with improved handling of incomplete Audible API responses.
