### ISSUE TITLE
Licence denied - no download possible

### ISSUE THREAD

**Issue by jschoen42** [audiamus/BookLibConnect#61]
since today (19.07.2022) I get **on all titles** "license_denied"

![Untitled-1](https://user-images.githubusercontent.com/108626845/179803123-7eaa6303-37a9-4080-b578-d5b88670eaaa.png)

errors are:
{"message":"1 validation error detected: Value 'Extreme' at 'quality' failed to satisfy constraint: Member must satisfy enum value set: [High, Normal]"}

[AudibleApi.GetDownloadLicenseAndSaveAsync] Id=498, "Code Black": **license_denied; license decryption failed**.

I have tested titles where the download was possible yesterday evening - now not possible

here some log files from today
[log.zip](https://github.com/audiamus/BookLibConnect/files/9143017/log.zip)

Jürgen

**UPDATE: I have changes the quality to "high" and now download is possible**

![Untitled-2](https://user-images.githubusercontent.com/108626845/179804878-79e2257c-52e6-4c8a-a993-33e3b7949d30.png)

**Comment by audiamus** [comment]
It seems they have reduced the quality option to two. With "high" I get 44100 Hz, 128 kb/s, with "normal" 22050 Hz, 32 kb/s for a recent title.

**Comment by ascheschleier** [comment]
changing the quality to "high" worked!

thank you!

**Comment by Borlean** [comment]
I was having the same error on version 0.9 and even tried downgrading to 0.8 with extreme. But changing the setting to 'High' worked.  Thanks!

**Comment by alurio** [comment]
HI 

Danke für den Thread, hatte gerade die Win 10 app deinstalliert und sogar meinen original Audible Key gesichert gehabt, trotzdem lief das Programm nicht, großer Schock. 

Schlage, vor in der nächsten Version die Qualitätsoptionen auf 2 anzupassen. Es gibt ja , zumindest bei mir tatsächlich nur 2. . Bei mir allerdings  high 44100 Hz, 128 kb/s, und  "normal" 22050 Hz, und  **64 kb/s**   wo die 32 her kommen irritiert mich etwas. bei mir sind alle Englischen Bücher mit 64 kbit manche, aber nur wenige mit 128 

Viele Grüße

**Comment by jschoen42** [comment]
möglicherweise kann man ganz auf die Auswahl verzichten - hat die Audible Website auch schon vor einiger Zeit gemacht. 

Die Win10 APP kann/konnte auch nur zwischen **standard** und **normal** umschalten
Bei der neuen APP AudibleSync habe ich gar keinen Umschalter gefunden

hier die Infos direkt von Audible zu ihren Audioformaten (in Deutschland)
https://magazin.audible.de/warum-hat-audible-ein-eigenes-format/

in USA gab es noch zusätzlich "Format 2" **(8 kbit/s)** 

"Extrem" (192 oder 256 kbit/s) gab es also so nie - Audible hat jetzt im Rahmen von AYCL (All-You-Can-Listen) ihre API etwas aufgeräumt

Jürgen

**Comment by alurio** [comment]
Ich wäre schon dafür die 2 Qualitätsstufen als Auswahl  zu belassen die Audible Apps fürs Smartphones unterscheiden ja auch zwischen normal und hoch. Und es scheint hier ja Benutzer zu geben, die bewusst in geringerer Qualität rippen. Davon abgesehen täte  Audible ein Update bei den Qualitätsstufen gut  2022 128 KBits noch als beste Option anzubieten ist etwas aus der Zeit gefallen. Dass war zu Napster Zeiten circa 2004 state of the Art und viele insbesondere altere amerikanische und Brittische  Hörbücher in 64 KBits klingen wie aus der Tonne. Zum Beispiel fast alle Discworld Titel, da wird's dann  mitunter unverschämt. Aber das liegt ja nicht im Einfluss von Auduamus, da muss Audible Hausaufgaben machen.

**Comment by audiamus** [comment]
Version 0.10, just released, lets you select "high" and "normal" only.
