### ISSUE TITLE
State image alt-text is just "image"

### ISSUE THREAD

**Issue by MartinKlefas** [audiamus/BookLibConnect#63]
I wasn't quite sure what each logo meant, and unfortunately when you mouse-over the status image it just says "image":
![Screenshot 2022-07-29 001004](https://user-images.githubusercontent.com/12558370/181652097-47fc1219-4496-47f6-8f3c-2caae30db4a0.png)

**Comment by audiamus** [comment]
Yes, it's the default tooltip. I have not looked into column- or cell-specific custom tooltips for the underlying DataGridView control but will put it on the to-do list.  

For the time being, here is a reference to all possible states and the associated icon:
```
public enum EConversionState {
    unknown,          // strikethru globe
    remote,           // globe
    download,         // globe with down arrow
    license_granted,  // key
    license_denied,   // strikethru key
    downloading,      // down arrow
    download_error,   // strikethru down arrow
    local_locked,     // lock closed
    unlocking,        // key over lock
    unlocking_failed, // strikethru key over lock
    local_unlocked,   // lock open
    exported,         // checkmark mauve
    converting,       // right arrow
    converted,        // checkmark green
    converted_unknown,// checkmark gray
    conversion_error  // strikethru right arrow
  }
```
(https://github.com/audiamus/BookLibConnect/blob/main/src/BooksDatabase.core/enums.cs)

**Comment by audiamus** [comment]
Meaningful tooltip added in version 0.11
