### ISSUE TITLE
it keeps on asking me for a code

### ISSUE THREAD

**Issue by Lina202208** [audiamus/BookLibConnect#66]
Hello,
I am in Canada. I tried both booklib and AAX convert and none of them work for me :-( Sorry I am a newbe and know very little if none to all that. Anyone who could guide me please?

**Comment by audiamus** [comment]
If you downloaded, converted and exported your book with Book Lib Connect, then AAX Audio Converter does not need a code, but formally, it insists. In this case, any dummy or placeholder code will do, like 12345678 or 00000000.
