### ISSUE TITLE
can not log in

### ISSUE THREAD

**Issue by typxxi** [audiamus/BookLibConnect#67]
I had been using Audiamus before (worked fine till at least eastern 2022 when I had been using it the last time).

Now I have learned that Windows App is no longer supported and went back to audiamus which had lead me to Book Lib  Connect, which I have installed for windows and installed a net 6.09 or whatever environment for I guess desktop apps.

Then I was able to start BookLibConnect but then I got an error during the registration: 

#1
If I start the app (german audible profile selected) and open the amazon login I get this error from amazon:  
Tut uns Leid: Die Web-Adresse, die Sie eingegeben haben, gibt es auf unserer Website nicht.

#2 
If I use the option 'with pre Amazon user' a valid audible web site opens to enter my id, credentials and a captcha.

But each time I have tried it I got an error 'userid / PW wrong' but it is right cause I had copied and typed that in what I had used in the browser for a usual audible login which there works fine. Any ideas ?

Here is the url that opens after clicking OPEN URL IN DEFAULT BROWSER (chrome latest version)
https://www.audible.de/ap/signin

Feels like the /ap/signin might no longer work due to missing app support since end of july or so.

I have not found any hint or solution about this topic which feels a bit stranged. Had purchased 1 or 2 books today for offline use in the RV without mobile connection but does not longer work with a laptop which I need due to sight issues cause I need big fonts. 

Hope there is a workaround, have put the issue also in the chat here but of cause in a shorter description
https://gitter.im/AaxAudioConverter/community?at=5f2438b986ad126839dc6ef7

Windows 10 has the latest updates from today, your app and the required runtime environment had been installed fresh today, but without a reboot which I will try now to make sure that it is not caused by that (and to let the other users know if that has been the cause).

Screenshot for #1  
![screenshot 2022-09-13 --- 22 02 36](https://user-images.githubusercontent.com/20662430/189998369-b73dee61-de2a-4207-954f-eb15b0bcf86e.jpg)

Screenshot for #2 
![screenshot 2022-09-13 --- 21 52 16](https://user-images.githubusercontent.com/20662430/189996411-1cf441be-b3da-4153-920f-ddd2c28b747d.jpg)

**Comment by audiamus** [comment]
> If I start the app (german audible profile selected) and open the amazon login I get this error from amazon:
Tut uns Leid: Die Web-Adresse, die Sie eingegeben haben, gibt es auf unserer Website nicht.

It may be misleading, but your Amazon login was actually successful. This is the anticipated positive result as stated in the Book Lib Connect dialog (in English) and also in the manual. Copy and paste the URL form this "Tut uns leid" page to the text box in the dialog.

**Comment by typxxi** [comment]
OK, 
I had not seen the dark greyish description or hint about the error topic but let's start from the beginning

the #2 version = 'with pre Amazon user' enabled seems no longer to work cause the url provided after the login attempt looks like a standard URL (https://www.audible.de/ap/signin) that BookLibConnect does not like after I had pasted it (I got an error)

BUT
it worked for #1 version (disabled option 'with pre Amazon user' ) the way you had described.

AND once I got through all the following settings I also got the manual which I had not read so far nor seen before, only the audiamus one which I had read before. Might be usefull to provide a link to the manual directly after installation success. Read this one again and then it reminded me that the login issue had already been before back in the Audiamus day if I am right.

Sorry
Thanks for the support.

**Comment by audiamus** [comment]
> the https://github.com/audiamus/BookLibConnect/discussions/2 version = 'with pre Amazon user' enabled seems no longer to work cause the url provided after the login attempt looks like a standard URL (https://www.audible.de/ap/signin) that BookLibConnect does not like after I had pasted it (I got an error)

You actually need a pre-Amazon Audible account to have any chance for this to work.

> it worked for https://github.com/audiamus/BookLibConnect/issues/1 version (disabled option 'with pre Amazon user' ) the way you had described.

OK. Good.

> Might be usefull to provide a link to the manual directly after installation success. 

Yes, perhaps the wizard pages should be reordered. On the other hand, people want to start right away, without being "distracted" by manuals.
