### ISSUE TITLE
Downloads keep failing

### ISSUE THREAD

**Issue by michael-zock** [audiamus/BookLibConnect#68]
Hi
I just installed the tool and everything seems to go as planned until I've clicked "Run" it's time to download the file for processing.
Happens every time, I can reproduce it. Doesn't matter if it's a single file, several or the contents of my entire library, not a single file gets downloaded correctly.

Not sure if it's connection errors and the software fails to resume downloads or something else, but the whole situation is damn frustrating. 
There's no longer an official native Windows client, OpenAudible is no longer "open" source but now a cash grab, Book Lib Connect turned out worthless since the program keeps freezing and BookLibConnect fails do download anything.

Hope there's a way to fix this, since I'm at my wits' end. 
**Thanks in advance for any help you can provide!**

[BookLibConnect_2022-09-24_002.log](https://github.com/audiamus/BookLibConnect/files/9638524/BookLibConnect_2022-09-24_002.log)

**Comment by audiamus** [comment]
The log file says: license_denied or download_error for the books. I would concentrate on a single book first where the message is download_error. Looks like an SSL error. The download did not start or not complete, for whatever reason. Did it start? Could be the internet connection. We also cannot rule out a temporary server issue, particularly with all the license_denied messages in the log. We had that before.       

One more thing: Is you computer system time correct? If not, it can hamper SSL/TLS communication.

**Comment by michael-zock** [comment]
Thanks, unfortunately even after syncing the system time manually (even though Windows is set to automatically sync it) and trying with just a single entry, the same problem occurs instantly.
I even picked one of those "free as part of the subscription" books to avoid one layer of possible DRM problems (compared to something purchased for a credit), to no avail.

[BookLibConnect_2022-09-24_002.log](https://github.com/audiamus/BookLibConnect/files/9638788/BookLibConnect_2022-09-24_002.log)

**Comment by michael-zock** [comment]
And an example with one purchased for a credit. Progress par appears, ends prematurely and I'm left with the same problem.
[BookLibConnect_2022-09-24_001.log](https://github.com/audiamus/BookLibConnect/files/9638794/BookLibConnect_2022-09-24_001.log)

**Comment by audiamus** [comment]
I believe these "free" books won't work. I'm not even sure whether they are encrypted at all, but Audible definitely does not respond with a license key like it does with the purchased books. 

But for the download issues: I really don't know. Not much I can do there. I invoke the download command from the .Net framework and wait for the result which happens to be an exception here. Is there anything unusual with your internet connection? The download says 314 MB. How far are you getting before the download aborts? Always at the same point? If not, try a shorter title, reduce the download quality setting and go for multi-part downloads.

**Comment by michael-zock** [comment]
Some of them now work, but others still don't, I'm at a success rate of about 10%.
The connection works fine with other programs like Jdownloader and browsers.
Guess I'll just have to write off this and other programs as not reliable.
