### ISSUE TITLE
Add option to add metadata about these

### ISSUE THREAD

**Issue by Rexadev** [audiamus/BookLibConnect#72]
1. Written by: 
2. Narrated by: 
3. Series: 
4. Release Date: 
5. Language: 
6. Publisher:

**Comment by audiamus** [comment]
Meta data manipulation is not within the scope of Book Lib Connect. Book Lib Connect is a mere downloader and decrypter. All conversion tasks are handled by AAX Audio Converter.

However, AAX Audio Converter will and shall only use standardized meta tags, both in the MP4 and MP3 tag environments. While both environments would allow proprietary tags, most if not all of the potential multi-media or audiobook players will ignore them.
