### ISSUE TITLE
Doesn't see complete library - can't see or download one book.

### ISSUE THREAD

**Issue by Drew4me** [audiamus/BookLibConnect#74]
Been using BLC for a little while, great work.

It won't see one item in my library though

Not sure why this one is the exception, but I wanted that book downloaded!

**Comment by audiamus** [comment]
Is the missing title a podcast? They are not yet supported. 

Or an "adult" title? The "adult" attribute, as set by Audible, is often quite strange. But you can show those titles by clicking the check-box.

**Comment by Drew4me** [comment]
Huh, the adult setting fixed it, but I didn't think it was adult!
It is listed as Fantasy, Romantic, Romantic Comedy. Hmmm.

**Comment by audiamus** [comment]
As I said, the _adult_ assignment can be weird. One user told me, he/she had a children's book marked that way. On the other hand, some of the "New York Times bestselling authors" have titles with rather explicit content which are not marked as _adult_, apparently.
