### ISSUE TITLE
"Run" button doesn't unlock

### ISSUE THREAD

**Issue by BratPfanneTV** [audiamus/BookLibConnect#76]
I don't know if I'm missing anything but the program, after working well for a bit, is now not letting me download anything because as soon as I add a book to the queue it gets the "download" state icon without actually letting me press the "Run" button, and then proceeds to not actually download anything. 
![image](https://user-images.githubusercontent.com/39345937/200244755-2f5d17e7-bff6-4838-834b-1d69fd52b279.png)
Is there something I'm doing wrong?

**Comment by audiamus** [comment]
The "Run" button will only be enabled if both the download folder and the export folder actually exist. If you configured them for an external disk, the path may not currently be available. Check both settings.

**Comment by BratPfanneTV** [comment]
Thanks, I had accidentally deleted the folder I had selected!

**Comment by MarcelvC** [comment]
I ran into the same problem and only figured it out after finding this old issue. It might be helpful to display a message to the user if either the download folder or the export folder don't exist.
