### ISSUE TITLE
Datenbank verliert Information über Download

### ISSUE THREAD

**Issue by enno22** [audiamus/BookLibConnect#8]
Hallo,

habe das Problem das heute plötzlich laut Datenbank kein Hochbuch heruntergeladen wurde, obwohl alle vorhanden sind. Gibt es einen Weg diese Makierung wieder zu setzen ?

**Comment by audiamus** [comment]
Das Programm prüft beim Start, ob die laut Datenbank heruntergeladenen und exportierten Bücher auch dort zu finden sind, wo der gespeicherte Pfad hinzeigt. Wenn dieser Pfad aber nicht verfügbar ist, z,B. externe Platte unter neuem Laufwerksbuchstaben oder NAS nicht erreichbar, dann wird der Status rückgesetzt, zunächst von "exported" auf "unlocked", evtl weiter auf "locked" und wenn alles nicht zu finden ist, ganz zurück auf "remote".

Könnte es sein, dass es eine solche Nicht-Erreichbarkeit gegeben hat? 

Wenn die Dateien bei einem späteren Start wieder gefunden werden, wird nicht erneut heruntergeladen, nur erneut exportiert.

Das Rücksetzen des Status wird im Moment noch nicht protokolliert, aber es scheint mir eine gute Idee, das einzubauen, damit man es ggf. nachvollziehen kann.

Die Datenbank ist SQLlite. Man kann sie sich mit jedem SQLite-Tool anschauen. Ist natürlich durch den relationalen Aufbau ziemlich kryptisch.

**Comment by enno22** [comment]
Hi, vielen Dank für die schnelle Reaktion. Ja der Download Ordner liegt auf einem NAS Laufwerk, da kann es gut sein das dies ab und zu nicht verfügbar ist. Ansonsten funktioniert das Tool schon wirklich gut, habe über 1000 Hörbücher und die wurden problemlos heruntergeladen und konvertiert.

**Comment by audiamus** [comment]
Das wird es sein. Aber ich werde da was ergänzen, dass man vielleicht ein solches Rücksetzen bestätigen muss.

Andere Frage: Bei 1000 Büchern: Wie ist die Performance beim Starten? Und hast Du die Sortierfunktion der einzelnen Spalten in der Buchliste mal ausprobiert?

**Comment by enno22** [comment]
Startet fix, auch das Sortieren funktioniert flüssig. Schön wäre es, wenn beim Herunterladen und Konvertieren die Anzeige mit dem aktuell geladenen Buch autoscrollen würde. Hatte alle Bücher in einem Rutsch makiert und nach den ersten Büchern nicht mehr gesehen an welchem Buch er gerade arbeitet.
Aber ich glaube dein Plan ist ja eine Software aus Book Lib und Audio Converter zu erstellen, deshalb nur der Hinweis mit der Datenbank :-)

**Comment by audiamus** [comment]
> Startet fix, auch das Sortieren funktioniert flüssig. 

Sehr gut. Das war ja dann ein Härtetest.

> Schön wäre es, wenn beim Herunterladen und Konvertieren die Anzeige mit dem aktuell geladenen Buch autoscrollen würde. 

Es wird ja mit der Integration in AAX Audio Converter wieder die Statuszeile geben, wo der Bearbeitungsfortschritt auch als Text angezeigt wird. Mit dem Autoscrollen ist das so ein Problem, denn die einzelnen Schritte können im Prinzip parallel ablaufen. Es wäre auch denkbar, mehrere Bücher gleichzeitig herunterzuladen, nur gibt das normalerweise keinen Performancegewinn.

Was jetzt schon parallel läuft, sind Herunterladen, Entschlüsseln und Exportieren. Bei langsamen und weniger ausgestatteten Laptop-Prozessoren kann u.U. das Entschlüsseln deutlich länger als das Herunterladen dauern. 

Man könnte natürlich alle Bücher oder Teile, an denen gerade gearbeitet wird, jeweils nach oben rücken, so wie es z.B. Zoom mit der Teilnehmerliste macht, und die momentanen Sprecher nach oben schiebt. Mal schauen, werde es auf die Wunschliste setzen.

Was auf jeden Fall bleiben und in AAX Audio Converter übernommen wird, ist die leicht veränderte Listenansicht im Hauptfenster. Die kann nun deutlich mehr als bisher. Und zukünftig soll man dann entscheiden können, ob man als Quelle lokale AAX-Dateien oder seine Bibliothek auf dem Server wählen möchte.

**Comment by enno22** [comment]
> Es wäre auch denkbar, mehrere Bücher gleichzeitig herunterzuladen, nur gibt das normalerweise keinen Performancegewinn.

Also bei mir hat er pro Buch mit ca. 150 MBit/s - 250 MBit/s geladen, wenn ich direkt über die Audible Seite per Webbrowser Hörbücher lade kann ich bis zu vier Bücher gleichzeitig laden. Da dann mit bis zu 500 MBit/s, ist natürlich immer abhängig vom ISP (Hier Vodafone Kabel 1 GBit).

> Was jetzt schon parallel läuft, sind Herunterladen, Entschlüsseln und Exportieren. Bei langsamen und weniger ausgestatteten Laptop-Prozessoren kann u.U. das Entschlüsseln deutlich länger als das Herunterladen dauern.

Das stimmt mein mobiler Core I7 hat bei entschlüsseln länger gebraucht, aber immer noch schneller als beim aax 2 mp3 konvertieren.

Schließe das Ticket hier mal, da ja kein richtiger Bug :-)

**Comment by audiamus** [comment]
> ist natürlich immer abhängig vom ISP (Hier Vodafone Kabel 1 GBit). 

Das ist gut zu wissen. Parallelisierung hier grundsätzlich vorzusehen war also schon richtig.

> aber immer noch schneller als beim aax 2 mp3 konvertieren.

Die Verschlüsselung ist ja AES. Und viele CPUs haben dafür Hardware-Beschleuniger. Die Konvertierung von AAC (das ist der entschlüsselte Audiodatenstrom sowohl bei AAX als auch bei AAXC) zu MP3 ist ein Transcoding, das auch nicht parallelisiert werden kann, aufgrund der Eigenschaften des schon etwas betagten MP3-Codecs. Erst wenn man die Datei aufspaltet, nach Kapitel oder feiner, kann AAX Audio Converter parallel arbeiten. Er startet dann mehrere FFmpeg-Prozesse, je nach Anzahl der Kerne der CPU. Das Handbuch von AAX Audio Converter enthält dazu eine Tabelle mit meinen Messergebnissen.
