### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by pacodiez** [audiamus/BookLibConnect#81]
Hello, first of all I'd like to give you the thanks for your work.

I am trying to make the initial profile but after login in Amazon, it shows this error page:

![image](https://user-images.githubusercontent.com/13199356/205094026-fa9bf5d8-48f8-4883-a687-316db095b731.png)

![image](https://user-images.githubusercontent.com/13199356/205093756-4728882c-4432-49ab-9077-a55ed3fa3a95.png)

It Happens the same in amazon.es and amazon.com (I have audible user in both domains)
In Amazon.com, the process to login success in AudibleSync app (Spain is not prresent for Amazon.es in AudibleSync).

Please, could you help me.

Thanks in advance

**Comment by audiamus** [comment]
This is the expected behavior. Your login succeeded. You now simply copy the URL form that page that claims not to exist back to the Book Lib Connect profile dialog to complete the process, just as the instructions on that dialog say.

**Comment by pacodiez** [comment]
OK, my clear mistake: not read carefully the instructions. Many thanks and congratulations for your work.
