### ISSUE TITLE
No longer shows new titles purchased after Jan 21, 2023

### ISSUE THREAD

**Issue by Sailfish** [audiamus/BookLibConnect#86]
When I invoke BookLibConnect it loads all titles except those I've purchased after Jan. 21, 2023.

Seems like Audible may have implemented some changes recently?

Note: I'm able to download the .aax files to my Sansa Clip and they still play okay, though.

-Log=4 log file attached.
[BookLibConnect_2023-01-24_001.log](https://github.com/audiamus/BookLibConnect/files/10497237/BookLibConnect_2023-01-24_001.log)

**Comment by audiamus** [comment]
The log says, the http request to update the library timed out. On the other hand, the cover image download succeeded. Can you download an older book? And have you tried a Resync?

**Comment by Sailfish** [comment]
Hmm, this is very odd. Now both those newer title show and BookLibConnect transcodes it as expected.

Note: I had a similar problem loading those titles' Kindle books and now they work fine.

Something janky going on with Amazon's servers?

**Comment by audiamus** [comment]
Could have been anything, e.g. servers down for maintenance or a denial-of-service attack.
