### ISSUE TITLE
Authorization failed. Please try again. 

### ISSUE THREAD

**Issue by bluedolphin0502** [audiamus/BookLibConnect#87]
Hello. 
When I copy the URL and then paste it, I received the error message of 'Authorization failed. Please try again.'

Can anyone help, please?

**Comment by audiamus** [comment]
Are you sure that you copied the **entire** URL _(or more correctly: URI_) back into Book Lib Connect? It's a very long one.

The log file may also contain a clue but might need log level 4.

**Comment by bluedolphin0502** [comment]
I clicked the button that says COPY URL, so shouldn't that have done the
whole thing?

Kind Regards,
Rach

**Comment by audiamus** [comment]
The URL that Book Lib Connect creates is the initial URL for your web browser. You log in to your Amazon account in your web browser with this URL. Once you get this misleading web page ("Looking for something? ..."), you are in. And the URL/URI of that web page contains all the parameters that Book Lib Connect needs to create the profile.

So, two **different** URLs:
1. The first one created by Book Lib Connect, to be used with your web browser
2. The second one shown in your web browser after a successful login  ("Looking for something? ..."), which you copy back to the text box in in Book Lib Connect.

**Comment by bluedolphin0502** [comment]
Thank you,
I'll try again tomorrow

Kind Regards,
Rach

**Comment by bluedolphin0502** [comment]
Looking for Something?
We're sorry. The Web address you entered is not a functioning page on our
site
 Go to Amazon.com.au's Home <https://www.amazon.com.au/> Page
*Rach*

**Comment by audiamus** [comment]
Yes, that's the one. As the Book Lib Connect new profile window, its tooltip and the manual say.

**Comment by audiamus** [comment]
Yes, that's the one. As the Book Lib Connect new profile window, its tooltip and the manual say.
