### ISSUE TITLE
Program will not launch

### ISSUE THREAD

**Issue by ARR4NN** [audiamus/BookLibConnect#93]
The program will not launch . Have AAX Converter installed and BookLibConnect

**Comment by ARR4NN** [comment]
Running windows 11

**Comment by audiamus** [comment]
It could be the .Net runtime not up to date like in #89.

Check the Windows Event Viewer > Windows Logs > Application. Any entries there, related to Book Lib Connect?

**Comment by ARR4NN** [comment]
![image](https://user-images.githubusercontent.com/70060472/219366497-913fe53a-06f6-4c45-9356-60745a6daafa.png)
![image](https://user-images.githubusercontent.com/70060472/219366515-84f9c6d0-85f6-4d75-80b4-706177075ebb.png)

**Comment by audiamus** [comment]
Well, looks very much the same as in #89. Try updating the .Net runtime:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.14-windows-x64-installer
