### ISSUE TITLE
BookLibConnect not displaying purchased titles past 2023-01-24

### ISSUE THREAD

**Issue by Sailfish** [audiamus/BookLibConnect#94]
On installing and invoking BookLibConnect 0.12 the Library display does not display any titles purchased after 2023-01-24 (18 in all). Attached is a screenshot of Library display as well as BookLibConnect 0.12 "-Log=4+. Note, I had not run BookLibConnect 0.11 after 2023-01-24 so I am unsure if this is related to the BookLibConnect version change. 

![BLC-0 12Library-20130305](https://user-images.githubusercontent.com/110050/222985008-e401f816-0b5b-4044-b650-5e359f0b4e39.jpg)
[BookLibConnect_2023-03-05_001.log](https://github.com/audiamus/BookLibConnect/files/10892910/BookLibConnect_2023-03-05_001.log)

**Comment by audiamus** [comment]
According to your log, the server request GetLibraryAsync () was cancelled after the timeout of 100s. Presumably a server issue, I suggest to try again later.

**Comment by Sailfish** [comment]
I've run BookLibConnect several times, the last being a few minutes ago Each time stopping at the same title. I have 1449 titles in my Library. Could this be either an Audible timeout limitation or, possibly, a title download restriction?

![Untitled - 1](https://user-images.githubusercontent.com/110050/222992550-981a749d-cbd5-4848-b6de-087071692f0c.jpg)
[BookLibConnect_2023-03-05_002.log](https://github.com/audiamus/BookLibConnect/files/10893243/BookLibConnect_2023-03-05_002.log)

**Comment by audiamus** [comment]
> it appears that there was some kind of timeout being set

Yes, that's what I said. It's a bit strange because that's very low level, as if the outgoing call is blocked, the server does not exist or not respond. And it is indeed a 100 secs later that the call expires. It also appears to be the first call to the server, as the refresh token call will be usually skipped. Are you using an internet proxy? Any recent changes to your network configuration? 

You can try DNS resolution, from a console, command prompt or PowerShell: 
`nslookup api.audible.com`

If that works, you can also try a full resynchronisation (the Resync button) but it will probably fail as well.

**Comment by Sailfish** [comment]
Below is the text from the response from the nslookup command:
//
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Dad>nslookup api.audible.com
Server:  76-14-0-8.sf-cable.astound.net
Address:  76.14.0.8

Non-authoritative answer:
Name:    d10x99kpkr7qkp.cloudfront.net
Addresses:  2600:9000:2146:8000:6:dc37:5251:70c1
          2600:9000:2146:e000:6:dc37:5251:70c1
          2600:9000:2146:dc00:6:dc37:5251:70c1
          2600:9000:2146:b200:6:dc37:5251:70c1
          2600:9000:2146:9c00:6:dc37:5251:70c1
          2600:9000:2146:3c00:6:dc37:5251:70c1
          2600:9000:2146:c400:6:dc37:5251:70c1
          2600:9000:2146:4600:6:dc37:5251:70c1
          65.8.162.92
Aliases:  api.audible.com
          tp.85cf8037a-frontier.audible.com
//

I had tried Resync and it fails as well

Regarding network changes, I recently moved from Spectrum/Charter (cable) to Astound (fiber). I hoping that it's not that since their call-in tech support is awful, strictly level 1 and if it requires any technical skills, they send out an unskilled technician and charges me $80 for the service, the service being that they confirm internet connection only.

I also got a new router eero to handle the increased bandwidth, 800Mbs over wire (ethernet). I will try using my old router as a last resort since switching routers always involves reconfigurations and complications.

I do have a Win10 laptop and will test BookLibConnect on it.

**Comment by Sailfish** [comment]
I ran BookLibConnect a few times today on Win7 and it returned the full results so I was hopeful. However, After running it several minutes ago, it failed again with the timeout error. It took a significant amount of time to complete, much more than when it succeeded other time today which I suspect may be the cause of the timeout condition. Looking at the full posting of the timeout line in the log, I'd almost suspect this error was coming from Audible's API; although, considering that this run was done late in the evening, I wouldn't have thought their servers were being taxed then (assuming they are are on Amazon's USA cloud servers.

Anyway, I'll install BookLibConnect on my Win10 laptop tomorrow and see if that makes a difference. I've attached to failed log file for your inspection.

Regards,
Pat

[BookLibConnect_2023-03-06_004.log](https://github.com/audiamus/BookLibConnect/files/10906381/BookLibConnect_2023-03-06_004.log)

**Comment by audiamus** [comment]
> Looking at the full posting of the timeout line in the log, I'd almost suspect this error was coming from Audible's API; although, considering that this run was done late in the evening, I wouldn't have thought their servers were being taxed then (assuming they are are on Amazon's USA cloud servers.

The nslookup response suggests the Amazon cloud. It could also be DoS attacks. Anyway, the Win 7 TLS version issue will arise eventually. The most recent standard for secure sockets, including https, is TLS 1.3, which is not supported by Win7 and never will be, according to what you find on that matter. When setting up a secure connection, the two socket peers negotiate a suitable protocol, but either side may insist on the highest possible level and won't accept TLS 1.2 any longer. I had this last year in my professional life in a totally different field, nothing to do with audio, and I remembered that yesterday.

**Comment by Sailfish** [comment]
I plan to pursue the Win10 option but it may be a dead end. I just re-ran BookLibConnect a few minutes ago on my Win7 desktop and it completed the full download in about 35 secs as near as I can tell. I've attached the log=4 below.

On first blush, it seems related to outside influences rather than my Win7 system. When it timed out last night, I immediately ran a speedtest and was well over 400Mbps over-the-air (wifi) and over 900Mbs to the router.

Best guess? I suspect that the timeout limit is something on Audible/Amazon's end and under heavy load conditions along with my large number of titles may trip their timeout limit. If so, the only possible solution that comes to mind would be to break the download in to multiple requests. However, just because I can type that in one sentence doesn't mean it is even feasible on your end.

I'll post again after running the Win10 experiment.

Regards,
Pat

[BookLibConnect_2023-03-07_001.log](https://github.com/audiamus/BookLibConnect/files/10910945/BookLibConnect_2023-03-07_001.log)

**Comment by audiamus** [comment]
The timeout issue is very low level. The client cannot reach the server or it cannot establish a secured session (while I'd expect a different err or for the latter, but remembering the problem I had last year, this may not be the case).

Anything else would give different errors, typically one of the 400s response codes. 

Book Lib Connect will breakdown the library download request in bundles of 100 titles per request, which you will see in the log file running a full resync. The default library download takes your last purchase date from the local database and passes that as an argument to the server, see line 87 in your latest log:
`[AudibleApi.sendForStringAsync] Before request, GET, https://api.audible.com/1.0/library?purchased_after=2023-03-07T00:35:49.996Z&num_results=100&page=1...`

**Comment by Sailfish** [comment]
I was able to bypass the Win10 registration using the replacement of the Configuration.json file but it ended up having to use a somewhat circuitous route (requiring multiple BookLibConnect restarts to get a fully-populated Profile.) Afterward, I was able to use BookLibConnect to download the complete library. Unfortunately, I was also able to do that using Win7 7, as well so it wasn't able to reveal much except, perhaps, that it's not a Win7 issue at this time? Note: I've re-enabled the "Encrypt configuration" option afterward.

Re: Resync: I'm a bit confused regarding this. When I first open BookLibConnect and select "Download" (Resync button not displayed), does it download all the titles at that time or does it just reformat the last downloaded titles for the display and selection? **_I'll need to try this again after I add another title_**, but I have been under the impression that it downloaded all titles since when BookLibConnect tripped the timeout, it was without me clicking the Resync button.

**Comment by Sailfish** [comment]
Thanks for explaining the Library display and Resync process. My uncertainty came about when experiencing the delay before displaying the title list which I now know is mostly caused by the rebuilding of the display and not having to re-download the library each time. I was able to further confirm this by purchasing another title today and then running BookLibConnect and seeing that the new title had not shown on the display list until I pressed the Resync button.

At this time I'm satisfied that Win7 is still a viable platform for BookLibConnect and will accept that the timeout issue is related to some external influences. Unless you wish me to provide further information, I am okay with you closing this issue.

**Comment by audiamus** [comment]
>  I was able to further confirm this by purchasing another title today and then running BookLibConnect and seeing that the new title had not shown on the display list until I pressed the Resync button.

It can take some time before a newly purchased title becomes available in your library.
