### ISSUE TITLE
Download Folder on setup

### ISSUE THREAD

**Issue by digitalw00t** [audiamus/BookLibConnect#95]
When I try to setup the the download folder, I get:
Unhandled exception has occured in your application.  

The system cannot find the file specified.

And I'm stuck on this part.

**Comment by comatron** [comment]
same problem - here is my JIT-debug-log:

"Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ComponentModel.Win32Exception (0x80070002): Das System kann die angegebene Datei nicht finden.
   at System.Windows.Forms.FolderBrowserDialog.CreateItemFromParsingName(String path)
   at System.Windows.Forms.FolderBrowserDialog.SetDialogProperties(IFileDialog dialog)
   at System.Windows.Forms.FolderBrowserDialog.TryRunDialogVista(IntPtr owner, Boolean& returnValue)
   at System.Windows.Forms.FolderBrowserDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.CommonDialog.ShowDialog()
   at core.audiamus.connect.app.gui.MainForm.setDirDialog(String olddir, String defaultSubPath, String caption)
   at core.audiamus.connect.app.gui.MainForm.setDirDialog(Func`1 dirSetSrc, Action`1 dirSetDst, String defSubDir, String caption)
   at core.audiamus.connect.app.gui.MainForm.setDownloadDir()
   at core.audiamus.connect.app.gui.MainForm.btnDnldDir_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll.
----------------------------------------
BookLibConnect
    Assembly-Version: 0.12.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.1423.7402.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.1423.7402.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.Primitives.dll.
----------------------------------------
audiamus.aux.core
    Assembly-Version: 2.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Specialized.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Drawing.Common.dll.
----------------------------------------
System.Threading
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.RegularExpressions.dll.
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.InteropServices.RuntimeInformation.dll.
----------------------------------------
System.Memory
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Memory.dll.
----------------------------------------
System.Text.Json
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Json.dll.
----------------------------------------
System.Text.Encodings.Web
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Encodings.Web.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Concurrent.dll.
----------------------------------------
System.Runtime.Intrinsics
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Intrinsics.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Numerics.Vectors.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Uri.dll.
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.Lightweight.dll.
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Primitives.dll.
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.ILGeneration.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Thread.dll.
----------------------------------------
System.Linq
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.dll.
----------------------------------------
System.Console
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Console.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Encoding.Extensions.dll.
----------------------------------------
audiamus.aux.win.core
    Assembly-Version: 2.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.common.util.core
    Assembly-Version: 0.3.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.connect.core
    Assembly-Version: 0.12.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.booksdb.core
    Assembly-Version: 0.6.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.connect.ui.core
    Assembly-Version: 0.12.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.1423.7402.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/Accessibility.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.TypeConverter.dll.
----------------------------------------
audiamus.common.types.core
    Assembly-Version: 0.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Loader.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.1423.7402.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/de/System.Windows.Forms.resources.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
audiamus.aux.propgrid.core
    Assembly-Version: 0.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Resources.Extensions.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.1423.7402.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Drawing.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ObjectModel.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.NonGeneric.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.ThreadPool.dll.
----------------------------------------
audiamus.aux.treedecomp.core
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Http
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Http.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Primitives.dll.
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.Tracing.dll.
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.DiagnosticSource.dll.
----------------------------------------
System.Net.Security
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Security.dll.
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.X509Certificates.dll.
----------------------------------------
System.Net.Sockets
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Sockets.dll.
----------------------------------------
Microsoft.EntityFrameworkCore
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Overlapped.dll.
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.NameResolution.dll.
----------------------------------------
audiamus.aux.win.dialogbox.core
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
audiamus.sysmgmt.core
    Assembly-Version: 1.2.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.Win32.Registry.dll.
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.Primitives.dll.
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Principal.Windows.dll.
----------------------------------------
System.Security.Claims
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Claims.dll.
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.Encoding.dll.
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.Algorithms.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Immutable.dll.
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.FileVersionInfo.dll.
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.Expressions.dll.
----------------------------------------
Microsoft.EntityFrameworkCore.Abstractions
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/netstandard.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll.
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Data.Common
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Data.Common.dll.
----------------------------------------
System.Transactions.Local
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Transactions.Local.dll.
----------------------------------------
Microsoft.Extensions.Logging
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Annotations
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.Annotations.dll.
----------------------------------------
System.Net.NetworkInformation
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.NetworkInformation.dll.
----------------------------------------
Microsoft.Data.Sqlite
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.core
    Assembly-Version: 2.0.6.1341.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly-Version: 2.0.6.1341.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
SQLitePCLRaw.provider.e_sqlite3
    Assembly-Version: 2.0.6.1341.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.EntityFrameworkCore.Proxies
    Assembly-Version: 6.0.7.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Castle.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.dll.
----------------------------------------
System.Reflection.TypeExtensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.TypeExtensions.dll.
----------------------------------------
System.Globalization
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Globalization.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Extensions.dll.
----------------------------------------
System.Reflection.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Extensions.dll.
----------------------------------------
System.Reflection.Emit
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.dll.
----------------------------------------
DynamicProxyGenAssembly2
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: file:///C:/Program%20Files/audiamus/Book%20Lib%20Connect/Castle.Core.dll.
----------------------------------------
System.Diagnostics.Debug
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.Debug.dll.
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Serialization.Primitives.dll.
----------------------------------------
DynamicProxyGenAssembly2
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: file:///C:/Program%20Files/audiamus/Book%20Lib%20Connect/Castle.Core.dll.
----------------------------------------
System.Linq.Queryable
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.Queryable.dll.
----------------------------------------
audiamus.audiible.json.core
    Assembly-Version: 0.5.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Xml.dll.
----------------------------------------
System.Formats.Asn1
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Formats.Asn1.dll.
----------------------------------------
System.Runtime.Numerics
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.1423.7309.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Numerics.dll.
----------------------------------------
HtmlAgilityPack
    Assembly-Version: 1.11.43.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------

************** JIT-Debuggen **************
"

**Comment by audiamus** [comment]
> same problem

So, the exception is indeed thrown where I suspected it. Do you have the default "Music" folder in your user directory tree? In Windows File Explorer, the folder icon typically is a musical note to mark it as a special folder. Book Lib Connect currently expects this folder to exist, since it is created by Windows automatically for each user.

If your default "Music" folder not exist, you can restore it:
https://www.elevenforum.com/t/move-or-restore-default-location-of-music-folder-in-windows-11.8712/

**Comment by digitalw00t** [comment]
That was the issue.  Honestly did NOT see that one coming.
