### ISSUE TITLE
Can't find the library after deleting/creating new profile

### ISSUE THREAD

**Issue by LamaDelRey** [audiamus/BookLibConnect#97]
Hi !

I managed successfully to download audiobook using my Audible profile. The problem is that I deleted the account and now Book lib can't find any books. I've done exactly the same process to create the new one. It's - if I understood correctly - because there is no 'new' book since last time.

I tried to desinstall/reinstall but Book Lib can't download the library since it has done it once.

My main goal is to get the famous 8 digits btw. :)

I don't know if it's possible to get it without downloading the books.

What should I do ?
Sorry for the confusion, not native at all.

**Comment by audiamus** [comment]
> My main goal is to get the famous 8 digits btw. :)

You won't need them when you download your books with Book Lib Connect. 

> I've done exactly the same process to create the new one. It's - if I understood correctly - because there is no 'new' book since last time.

You probably tried a full resync?

It something went wrong with the library update, the log file and the temp. json files should have some information, `C:\Users\<your user name>\AppData\Local\audiamus\BookLibConnect`, subfolders `log` and `tmp`.

To really start from scratch when installing anew, you should also delete you local library database that Book Lib Connect created. You could keep your profile configuration, though, to avoid registering a new device again. 

Go to `C:\Users\<your user name>\AppData\Local\audiamus\BookLibConnect` again. In subfolder  `data` delete `audiobooks.db.` You can keep the other files and folders. Not that `config` holds you profiles and access tokens which you may not want to delete. (It's in encrypted form, unless you actively opted for clear text.)

**Comment by audiamus** [comment]
I close this for now. Please reopen if the problem persists.
